### ISSUE TITLE
read the docs build is broken

### ISSUE THREAD

**Issue by joka** [liqd/adhocracy3#1186]
https://readthedocs.org/builds/adhocracy3mercator/2868762/

**Comment by nidico** [comment]
This now fails differently: https://readthedocs.org/builds/adhocracy3mercator/2890669/

**Comment by pallix** [comment]
We get ```
Could not import extension repoze.sphinx.autointerface (exception: No module named 'repoze.sphinx')``` error. Any idea @joka ?

**Comment by xi** [comment]
I created a workaround in #1488. I think it is possible to install the required extension, but I did not manage to do that yet. I guess I need additional permissions for that. Who can grant me owner rights to the readthedocs project?

**Comment by joka** [comment]
> created a workaround in #1488. I think it is possible to install the required extension, but I did not manage to do that yet. I guess I need additional permissions for that. Who can grant me owner rights to the readthedocs project?

you are now also maintainer

**Comment by joka** [comment]
> We get Could not import extension repoze.sphinx.autointerface (exception: No module named 'repoze.sphinx') error. Any idea @joka ?

maybe its just missing in the requirements files
