### ISSUE TITLE
Minimal thentos integration

### ISSUE THREAD

**Issue by mf59816** [liqd/adhocracy3#1349]
I would like to try and get thentos to work as a man-in-the-middle for the a3 rest api with minimal interference in frontend and backend.  This is the result of a discussion with @nidico and @joka.

### thentos as proxy (rest only)

html / css / js / ... are all delivered from the a3 frontend to the browser as before.  Thentos has no part in this.  All rest requests from the browser are sent to the backend, but are intercepted by thentos.  As a general rule, requests on user resources or session management are processed by thentos, and requests regarding other resources are passed through.  For example, `/principals/users/` would be handled by thentos; `/proposals/owiehgo` would not.

Observed by the frontend, user creation is handled by thentos in exactly the same way as by the backend today.  (This is the absolute minimal integration; it will get more interesting once we change this behavior and e.g. add single-sign-on-services.)

Observed by the backend, thentos will create a user so that group and role information can be maintained by a3 as before.  However, the backend will not have to do the email confirmation dance.  (A flag in the configuration files should be provided, and if that flag is checked, a user will be created with 'activated' flag checked right away.)

### changes to the frontend so far

Making the error messages from thentos look like those from colander may be more work than changing the frontend to be more lenient in its error message parsing.  I will look into what is expected from the error messages and may write a pull request soon, (unless you have objections at this point already).

### SSO and changes to the frontend

In order to introduce SSO (e.g. against github), we need to provide two javascript functions: one for handling `login with github` button clicks, and one for handling the route that github is redirecting back to after successful auth token generation.  These two functions can be provided from a new endpoint operated by thentos and delivering a javascript file.  The frontend would merely need to bind the two functions to the button event and route, resp.

Open questions: (1) how can this be done in a downwards-compatible, customizable way?  (2) what are the unexpected effects e.g. on token validity checks?

This is for your information and of course also a request for feedback; we will probably come back and bother you again soon with more on this.  (-:

thanks & good night!

Cc: @ChristianSi, @fhartwig

**Comment by nidico** [comment]
> I will look into what is expected from the error messages and may write a pull request soon

Fine. Error handling isn't great anyway currently.

**Comment by nidico** [comment]
> (1) how can this be done in a downwards-compatible, customizable way?

I don't expect backwards compat issues (apart from required migrations on existing platforms). You?

In what sense customizable? Change github to shibboleth? Atm, we can just add it as optional feature modules.

> (2) what are the unexpected effects e.g. on token validity checks?

Don't see any, if Thentos mimics the backend API or even uses it itself for session management. (Don't know whether I prefer having the session in Thentos only or also in the A3 backend; Thentos only feels better; do we need the session in the backend?).

**Comment by ChristianSi** [comment]
> (2) what are the unexpected effects e.g. on token validity checks?

I think the A3 backend will need a flag "behind-proxy". If true, the backend simply doesn't check the "X-User-Token" header and blindly believes the "X-User-Path" header. That should be fairly trivial to implement in the backend.

**Comment by joka** [comment]
> I think the A3 backend will need a configuration flag "behind-proxy". If true, the backend simply doesn't check the "X-User-Token" header and blindly believes the "X-User-Path" header. That should be fairly trivial to implement in the backend.

The proper way would be to use the pyramid.authentication.RemoteUserAuthenticationPolicy, 
beside this we need to figure out how sending messenges should work.

**Comment by mf59816** [comment]
the easiest way would be this: when the user is created on the a3 backend (with email confirmation switched off), the email address is left intact, so the backend can send emails the same way it does it now.

or am i missing something?

**Comment by joka** [comment]
> the easiest way would be this: when the user is created on the a3 backend (with email confirmation switched off), the email address is left intact, so the backend can send emails the same way it does it now.
> 
> or am i missing something?

no, if we store the right email and name you are right.

**Comment by ChristianSi** [comment]
Thentos can now be used as a transparent proxy that sits between the A3 frontend and backend without either A3 component noticing anything unusual. Thentos intercepts user creation and login requests and handles them by itself. A user is still created in the backend, but with some data (such as password) replaced by dummy values.

The necessary change to A3 (option to disable token validation) is implemented and merged.

Things that aren't working yet:

* Unhappy flows -- the errors returned by Thentos differ from those returned by the backend.
* Password reset -- there is a [ticket](https://github.com/liqd/thentos/issues/168) for it, but it remains to be seen when we'll actually need it..

**Comment by xi** [comment]
> Password reset -- there is a ticket for it, but it remains to be seen when we'll actually need it..

If it is not needed we still need to be able to remove it from the frontend.

**Comment by ChristianSi** [comment]
We'll probably need it at same point, but the initial focus might be on SSO solutions where all the user data comes from an external source, e.g. GitHub. That'll need changes to the frontend anyway.

**Comment by nidico** [comment]
> Password reset -- there is a ticket for it, but it remains to be seen when we'll actually need it..

I'd say we need it as soon as we go productive with this. Password reset is one of the important user management features. (I'm aware that A3 didn't implement similarly important features such as change of email address until now, but this is a major flaw already which should be fixed as soon as possible)

Continuing that discussion in liqd/thentos#168. In my opinion we should keep this issue here (minimal thentos integration) open as long as this isn't fixed.

**Comment by nidico** [comment]
Ah, now I read "We won't need that for SSO" in the [thentos ticket #168](liqd/thentos#168). Understand - the first process with Thentos will only use SSO. If this is indeed the minimal integration than we don't strictly need password reset for the first production installation and can close this ticket earlier - e.g. when password reset is removed or changed in the frontend and if the other issues are fixed.

**Comment by ChristianSi** [comment]
I now modified Thentos to mimic the errors emitted by the A3 backend. The general error structure is the same (when running in thentos-adhocracy mode) and the important error cases that occur in case of user creation, activation and login mimic those from the backend exactly.

Therefore, not only the happy but also the unhappy flow now works.

I'll work on password reset next as I guess we'll need it sooner or later.

**Comment by xi** [comment]
Sounds great!

Do you have any Thentos installation documentation? I would like to test it myself (in the unlikely case that I have some time on my hands...)

**Comment by ChristianSi** [comment]
@xi Yeah, checkout the [repo](https://github.com/liqd/thentos) and follow the install instruction in the [README](https://github.com/liqd/thentos/blob/master/README.md). Also, the header of [thentos-adhocracy/devel.config](https://github.com/liqd/thentos/blob/master/thentos-adhocracy/devel.config) documents the necessary changes in the A3 config.

To actually start thentos in proxy mode, do

```sh
$ cd thentos-adhocracy/
$ cabal run thentos-adhocracy'
```

I'm going on vacation now, but somebody from the Thentos team will hopefully be around to answer questions. There is the `#thentos` IRC channel in Freenode where we can be usually found.

**Comment by 2e2a** [comment]
Not relevant anymore.
