### ISSUE TITLE
Users with only local roles lose session

### ISSUE THREAD

**Issue by nidico** [liqd/adhocracy3#1371]
I haven't done a proper analysis, so I just write down the current symptoms.

In a current staging installation, users which only belong to a group which only has local roles assigned (moderator and initiator in this case), the session of these users automatically expires on reload of the page.

**Comment by xi** [comment]
The frontend does a head request to the root resource to verify its credentials. If it fails, it throws away the credentials.  Maybe this is what happens here.

**Comment by 2e2a** [comment]
Could not reproduce. Seems to be fixed.
