### ISSUE TITLE
Load more button not shown

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy3#1384]
on mercator staging the load more button is not shown anymore

**Comment by xi** [comment]
maybe related to #1622

**Comment by xi** [comment]
also related to #1010

**Comment by Johnschmidfront** [comment]
@2e2a and I verified that, when in a pool query `sort` is set (to something relevant, like `item_creation_date`), the `count` is restricted by the `limit` parameter and fails to return the total count.

**Comment by Johnschmidfront** [comment]
duplicate of  #1622
