### ISSUE TITLE
comments and documents in logbook dont seem to be in right order

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy3#1413]
both dont seem to be ordered creation date - is this a backend or a frontend task?

**Comment by MagdaN** [comment]
fixed it for the logbook

**Comment by pallix** [comment]
If I understand correctly you should be able to use `'sort': 'item_creation_date'` in the REST API, with eventually `'reverse': True` to get what you want.

**Comment by MagdaN** [comment]
yes, i implemented that

**Comment by xi** [comment]
> fixed it for the logbook in frontend

Could you please reference the pull-request/commit and close this issue? Or is there still something to do?

**Comment by MagdaN** [comment]
well, the problem still appears in the comment listing

**Comment by xi** [comment]
To clearify: The top level comments are expected to be ordered by item creation date, but they are not.

**Comment by pallix** [comment]
But it's only a frontend problem right?

**Comment by xi** [comment]
See also #725

**Comment by der-john** [comment]
problem was solved somewhere.
