### ISSUE TITLE
Activation link can be clicked only once

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3#1459]
The activation link sent to the user by email can only be click once, otherwise an error is displayed. It can be confusing for the user, since he may click once without noticing and then wondering why an error is displayed.

**Comment by nidico** [comment]
What's your proposal?

**Comment by pallix** [comment]
I retried and can't reproduce it. @slomo and @joka mentioned a few months ago that the link can only be clicked once but this does not seem to be  the case anymore.

**Comment by slomo** [comment]
So this is still an usability issue. Possible solutions:

 - Only activate account after user deliberately clicked an "activate now" button on the website
    - Need to be implemented in frontend
 - Display a this account has already been activated message when a used activation link is clicked
   - Needs flag for activation tokens if they were used
   - Activation used activation tokens can then be purged after a week
   - Need also support for this in frontend

**Comment by xi** [comment]
Related to #971

**Comment by der-john** [comment]
On clicking on an invalid activation link, (post #2748) the user receives an email saying "this account has probably already been activated".
