### ISSUE TITLE
Moderator cannot edit proposals in draft phase in alexanderplatz

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3#1573]
Although they have the good permissions, moderators cannot edit proposals in alexanderplatz in draft phase. No edit "button" is displayed.

This is not very problematic now since we are editing the proposals ourself but this is strange bug here that I would like to fix since it may cause serious problems later.

It can be reproduced with the JSON files that creates the alexanderplatz productive instance.

It may be related to #1557 

It's probably not related to #1549 since the roles are reordered in the matrix.

**Comment by xi** [comment]
Can not reproduce.

**Comment by pallix** [comment]
Did you try on `/alexanderplatz/workshopverfahren-2015` (not on  `/organisation/alexanderplatz`) once the resources and the local roles are created?

**Comment by joka** [comment]
If we fix this, we should also undo #1527

**Comment by joka** [comment]
> It can be reproduced with the JSON files that creates the alexanderplatz productive instance.

Where is these file? in bitbucket.org:liqd/server_config_salt_foucault.git  I cannot find it.

**Comment by xi** [comment]
>> It can be reproduced with the JSON files that creates the alexanderplatz productive instance.
>
> Where is these file? in bitbucket.org:liqd/server_config_salt_foucault.git I cannot find it.

local/pillar/prod/servers/berlin-adhocracy3-prod.sls

**Comment by slomo** [comment]
No clue why I came across that issue. Given its age and non reproducibility I will close now.
