### ISSUE TITLE
Coherent spelling of everything (process types, names, organizations etc.)

### ISSUE THREAD

**Issue by nidico** [liqd/adhocracy3#1618]
We have different methods of spelling process types, names, organizations etc. without much logic, e.g.:

- some german terms and names from the problem domain are translated to english (e.g. not_realizeable badge), others are used in the original form (e.g. burgerhaushalt)
- some are plural (e.g. bplaene) some are singular
- different ascii conversions or used (e.g. bplaene, burgerhaushalt)
- some are camel case, some not (e.g. *meinBerlin* in frontend vs. *meinberlin* in backend).

We should investigate the different usages, define a clear policy and migrate everything.

**Comment by xi** [comment]
- singular
- umlaut to ae, ue, …
- for meinberlin, no camelCase

**Comment by pallix** [comment]
For the first point of @xi, do we really want to mix german and english words in the source code?

**Comment by xi** [comment]
My point was more about things like "Stadtform" or "Kiezkasse". Translating common words like "Senatsmitarbeiter" to "office_worker" seems ok to me. But I see that this distinction is not very clear.

**Comment by xi** [comment]
this has been fixed in the frontend. @pallix @joka is more work needed in the backend or should this be closed?

**Comment by pallix** [comment]
Backend is not up to date wrt. to this policy. For example "kiezkassen".

**Comment by joka** [comment]
We cannot update the backend without migrating the database and adapt frontend code.
So I`m in favour of closing this issue. We can use it as a policy for new resources

**Comment by xi** [comment]
It seems like this won't be fixed in the backend, so this issue can be closed. Still I would like to add these guidelines to our documentation.
