### ISSUE TITLE
Make initial redirect configurable

### ISSUE THREAD

**Issue by slomo** [liqd/adhocracy3#1640]
I have a few installations where the default redirect points to bogus locations, while it is any expected to be replace by a list of process in the future I'd like to have finer control for now.

**Comment by xi** [comment]
I think there are 3 distinct issues here:

- #1378 introduced a config option that controls whether we link to a platform on register/password-reset or not. Maybe some link was overlooked there.

- In some places, the default for `adhTopLevelState.goToCameFrom()` is `"/"`. On `/` we usually redirect somewhere. This is configured in Adhocracy.ts with `adhTopLevelStateProvider.when("", …)`.

- When a user clicks on the "content" icon in the space switcher while already being in the content space, they are send to some url. This url is configured in Adhocracy.ts with `adhTopLevelStateProvider.space("content", …)`.

I propose to add config options for the last two bulletpoints.

**Comment by xi** [comment]
> In some places, the default for adhTopLevelState.goToCameFrom() is "/". On / we usually redirect somewhere. This is configured in Adhocracy.ts with adhTopLevelStateProvider.when("", …).

would it help to redirect to `initialUrl` (set in plain/context embeds) instead?
