### ISSUE TITLE
strange badge assignment deletion behavior

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3#1693]
Say I have a proposal with a deleted badge assignment. Now I want to assign the same badge again. I currently see two options how this can be achieved:

1.  The backend allows to create a new assignment with the same badge as the deleted one.
2.  The frontend finds the deleted badge assignment and undeletes it.

Option 1 is currently not implement, i.e. the backend prohibits the creation of assignments with same badge and object, even if one of them is deleted. This behavior is not completely wrong, but it may not be what you expect.

Option 2 is hard to do because I can not easily see which (if any) assignment has the desired badge (or can I?).

For the short term I would recommend to not delete badge assignments. But I guess we need something better in the long run.

**Comment by pallix** [comment]
The badge assignment has a badge field, so it should be possible to search for assignment of a specific badge with a search.

**Comment by xi** [comment]
Fixed via #2336
