### ISSUE TITLE
Create a core proposal form style

### ISSUE THREAD

**Issue by localgrr** [liqd/adhocracy3#1694]
We keep on duplicating proposal form styles, this should be in core

**Comment by xi** [comment]
I think as a step it would be good to have some statistics of

-   which kinds of proposals do we have?
-   how similar are they?
-   home much code do we have for each one?

**Comment by xi** [comment]
Current state:

-   `proposal-form` in core
-   `document-form` in core
-   `s1-proposal-form` in s1
-   `mercator-proposal-form` in mercator
-   `meinberlin-bplan-proposal-form` in meinberlin

IMHO we should not have a core proposal form style, but rather components from which a proposal form can be composed (e.g. inputs, erros messages, jump navigation, …)

**Comment by xi** [comment]
As written in the previous comment, we have already made significant improvements, but we do not necessarily work towards a proposal form style, but rather reusable form components. Closing
