### ISSUE TITLE
Invalid content type for geo document version on alexanderplatz

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3#1696]
Initial versions of geo documents have the invalid `IDocumentVersion` content type instead of `IGeoDocumentVersion`. 

https://embed.mein.berlin.de/api/alexanderplatz/workshopverfahren-2015/document_0000009/VERSION_0000000/

https://embed.mein.berlin.de/api/alexanderplatz/workshopverfahren-2015/document_0000009/VERSION_0000001/

The other versions seem okay (to verify).

Related to #1695

**Comment by pallix** [comment]
This is not critical as the first version is not used by the frontend.

**Comment by 2e2a** [comment]
Is fixed.
