### ISSUE TITLE
remove ResourceWidget

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3#1711]
The resourceWidget concept was a failed attempt to get more structure into the frontend code. It is overly complex and has only been used for comments and mercator proposals. We should refactor this to use the newer `bind_path`/`post_create`/`post_edit` concept and remove the  resourceWidget module.

**Comment by xi** [comment]
I started refactoring comment in 2015-10-tb-refactor-comment

**Comment by der-john** [comment]
I've considered it and decided the cost was too high. @xi and I think the `resourceWidget` module should be moved to `mercator`, though.

**Comment by der-john** [comment]
In my opinion, this is not worth doing unless AE2017 uses a3.

**Comment by der-john** [comment]
That's as far as we should go.
