### ISSUE TITLE
Sending bplan form while logged in

### ISSUE THREAD

**Issue by slomo** [liqd/adhocracy3#1713]
If you are logged in while attempting to send a bplan, the email validation of the form will fail. It can be tested with the example bplan form on berlin stage (this will send an email to Ingrid).

https://embed-meinberlin-stage.liqd.net/embed/mein-berlin-bplaene-proposal-embed?path=https:%2F%2Fembed-meinberlin-stage.liqd.net%2Fapi%2Fbplan%2FBspBPlan%2F

**Comment by xi** [comment]
Cannot reproduce.
