### ISSUE TITLE
Restore version optimization in backend

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3#1735]
Restore version optimization in backend with

- [ ] proper event handling

      We are missing an event for "Create item versions finished".
      A general solution for this is complicated: 
     There is the empty first version  and in batch request there can be multiple 
     requests creating item version".  In this context we should 
     also  remove the empty first version that is needless anyway.
     But at the moment we need this only to send notifications about created bplan 
     versions and this is working now. So i would not invest time in this now.
   
- [x] bplaene working #1729 

- [x] permissions checks working #1723

- [x] tests working with batchmode?
   - more unit/integration tests added

Also related to #1733

**Comment by joka** [comment]
@pallix thanks for this nice issue

**Comment by joka** [comment]
Pull request is here #1858
