### ISSUE TITLE
Name conflicts when creating users

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3#1738]
We still have name conflictings, in the user pool, when creating users.

For exemple this user name:

`name: 0000000_2015-10-12T11:16:39.393017+00:00`

**Comment by pallix** [comment]
Maybe Yves did forget to run manually the command from #1587.
We need to avoid manual migrations as there are a lot of installations from a3.

**Comment by joka** [comment]
> Maybe Yves did forget to run manually the command from #1587.
> We need to avoid manual migrations as there are a lot of installations from a3.

I updated the migration steps to update the user_name index autoamtically.

Is this problem solved now?

**Comment by 2e2a** [comment]
Hard to reproduce or understand what went wrong on the installation.

Closing it now and will look into it, if it occurs again.
