### ISSUE TITLE
Installation documentation is confusing wrt. to Python

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3#1741]
The installation instructions state that it is required to compile python and PIL, but is indeed not mandatory.

**Comment by nidico** [comment]
While at it, we should mention that Adhocracy 3 requires Python 3.4 or 3.5.

**Comment by joka** [comment]
we changed the documentation. The default  installation way is no by virtualenv because Python 3.4+  
is supported by most operation systems.

**Comment by joka** [comment]
PIL is still mandatory
