### ISSUE TITLE
Invalid error when providing x-user-token without x-user-path

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3#1753]
When making a request to the backend without providing `x-user-path` the backend returns an error indicating that the `x-user-token` is invalid.

`curl -X POST -d @filename.txt http://localhost:6541/principals/users -H "Content-Type:application/json" -H 'X-User-Token: d717a323a2e3e938c61a5e7acb5a326a9a6357a8c9cf26c6eeeb475a8d7d42bed334f54e1abf7fceba5588f312c57bbbca0a7f3b36709cdeef1fffe9c8e57ef4'
{"status":"error","errors":[{"location":"header","name":"X-User-Token","description":"Invalid user token"}]}   
`

**Comment by joka** [comment]
We could remove the x-user-token, 
its not needed anyway.

**Comment by xi** [comment]
Fixed by #2085
