### ISSUE TITLE
Bplan widget fails if path contains trailing slash

### ISSUE THREAD

**Issue by nidico** [liqd/adhocracy3#1761]
If I embed a bplan which has been created in #1749, it doesn't show any content if the bplan resource has a trailing slash.

Interestingly, this doesn't seem to be an issue when trying to embed a [public bplan](http://www.stadtentwicklung.berlin.de/planen/b-planverfahren/de/oeffauslegung/9-60/) with a trailing slash.

**Comment by xi** [comment]
Can not reproduce
