### ISSUE TITLE
Vagrant file out of date

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3#1773]
The vagrant file mentioned in the installation instructions is out of date. It refers to `bin/py.test_run_all` for example, which does not exist anymore. Maybe other things are out of date?

Who should maintain this? Maybe we should remove it from installation instructions or specify that it's not officially supported?

**Comment by xi** [comment]
The vagrant file is not maintained and AFAIK it has not been used at all. So I am in favor of removing it from the docs.

**Comment by joka** [comment]
> The vagrant file is not maintained and AFAIK it has not been used at all. So I am in favor of removing it from the docs.

ok, If its not used or testet we should remove it..

**Comment by pallix** [comment]
from the doc or from the doc and from the code?

**Comment by joka** [comment]
> from the doc or from the doc and from the code?

both
