### ISSUE TITLE
Icons have gone weird

### ISSUE THREAD

**Issue by local-girl** [liqd/adhocracy3#1781]
Absolutely weird in Meinberlin, new flag icon missing in Mercator - investigating others

**Comment by local-girl** [comment]
Icons are not building properly somehow in  Meinberlin, not sure if its just that site, if I go to ```/home/caroline/www/adhocracy3/src/meinberlin/meinberlin/build/icons``` and run ```fontcustom``` from there then the icons are OK, I'm not sure what the problem is it's like ```merge_static_directories``` isnt copying over the icons @xi can you have a look please - i have seen this on other sites

**Comment by xi** [comment]
I rebuilt all iconfonts in #1818. Does this help?

It may be a good idea to include building the iconfonts in buildout. It should be reasonably fast (buildin dirty checking) and could save us a lot of headaches.

**Comment by local-girl** [comment]
I believe this is fixed now, havent encountered this in a while
