### ISSUE TITLE
Have a specific database for each project

### ISSUE THREAD

**Issue by local-girl** [liqd/adhocracy3#1782]
databaseis always written to var/Data.fs could it be say for mercator var/mercator/Data.fs to remove the need to restart supervisorctl and delete the database every time one switches sites - at least in development

**Comment by pallix** [comment]
@slomo made the same suggestion. I would like too.

**Comment by MagdaN** [comment]
me too

**Comment by joka** [comment]
There different solutions, for example:

- just  copy the Data.fs file with wanted test data
- have a separated git checkout for every platform
- generate a  special development.ini  files for every platform.

**Comment by pallix** [comment]
Fourth solution have something like `    path $INSTANCE/var/dbs/$PROJECT/Data.fs` into `zeo.conf`?

**Comment by joka** [comment]
> Fourth solution have something like path $INSTANCE/var/dbs/$PROJECT/Data.fs into zeo.conf?

yes

**Comment by xi** [comment]
Fixed by #2170
