### ISSUE TITLE
We need a network folder so designers can share images with us

### ISSUE THREAD

**Issue by local-girl** [liqd/adhocracy3#1800]
it's too cumbersome doing it in user stories

**Comment by xi** [comment]
@slomo has work on this at some point. I am not sure how far he got.

**Comment by slomo** [comment]
I think this is no a3 feature. Never the less we had a story for the is the backlog, maybe it should just be brought up again. I can give some infos on what is there if somebody wants work on this.

**Comment by pallix** [comment]
Closing because not related to A3
