### ISSUE TITLE
Error when building a3

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3#1833]
I have errors when executing `buildout` for a3:

``
/bin/sh: line 2: 17225 Aborted                 (core dumped) /home/alphonse/projects/adhocracy3.mercator/bin/tsc --module commonjs --sourcemap src/mercator/mercator/build/js/mkResources.ts
``

The error comes from the `tsc` script:

```
cat bin/tsc
#!/usr/bin/env node
require('../lib/tsc.js')
```

The problem is that at this point of the installation, if followings the installation instruction, `node` is not in the PATH from the user. ` source ./source_env` is typed after the buildout is executed.

Is the proper solution to type this command before the build and to we update the doc?

**maybe I have a problem with my python environment, needs to investigate**

**Comment by joka** [comment]
> Is the proper solution to type this command before the build and to we update the doc?
If this helps we should add this to the installation instructions,
if this is the proper solution i cannot say without more investigation.

**Comment by pallix** [comment]
Ok the problem was that I had an old python compiled from the submodule installed in `bin/python` but I was using another python via `pyenv`.

Deleting `./bin/*` and `.installed.cfg` and boostraping + rebuilding everything worked.

**Comment by joka** [comment]
Quoting Pierre Allix (2015-11-19 14:57:24)
> Ok the problem was that I had an old python compiled from the submodule
> installed in bin/python but I was using another python via pyenv.
> 
> Deleting ./bin/* and .installed.cfg and boostraping + rebuilding everything
> worked.

fine, removing .installed and /bin is always a good idea to have a clear restart
with buildout.
