### ISSUE TITLE
filters and sort should not be in actionbar

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy3#1840]
I think while moving stuff from the column to the content there was some misunderstanding - not everything should go into one actionbar. Things like filter,sort and the switch to switch between different views (list,tiles, map) should go to the list (we could define that as a list-actionbar). Other things like edit, delete, print, report etc. that belong to a resource should go to a 'resource action bar'.  In the new design both 'bars' have different designs.

**Comment by local-girl** [comment]
I believe this is not an issue any more. Filter and sort is still part of listing as it always was.
