### ISSUE TITLE
AE: Edit/delete proposal links shown despite not being logged in

### ISSUE THREAD

**Issue by nidico** [liqd/adhocracy3#1851]
On AE with adhocracy3-0.4.1, the proposal detail view shows edit and delete links despite not being logged in.

Most likely this is just a frontend issue.

**Comment by local-girl** [comment]
Isn't the idea they can do these things but are redirected to login ? @xi ?

**Comment by xi** [comment]
Was probably introduced with the action bar.

> Isn't the idea they can do these things but are redirected to login?

Yes, but only if the action would be available to a "normal user". Editing proposals is typically restricted to creators and admins.

**Comment by MagdaN** [comment]
@joka @xi  : How can I figure out, if a user is allowed to edit. I created three users and one of the users created a proposals but all users have the same rights concerning the proposal.

{"OPTIONS":true,"PUT":false,"GET":true,"POST":true,"HEAD":true,"delete":false,"hide":false,"loggedIn":true}

**Comment by pallix** [comment]
Fixed by #1942
