### ISSUE TITLE
Pictures in AE are too big for planned column-width

### ISSUE THREAD

**Issue by stadine** [liqd/adhocracy3#1852]
<img width="1169" alt="bildschirmfoto 2015-11-25 um 11 47 41" src="https://cloud.githubusercontent.com/assets/7421063/11395307/85c6b06e-936a-11e5-9747-9bbdc09ffb3b.png">

**Comment by xi** [comment]
adding some `max-width: 100%` somewhere should be sufficient. @local-girl can you have a look?

**Comment by joka** [comment]
Not related sidemark:

The  user can upload one image but this is use cropped to two  very different aspcect ratio (small thumbnail in listing, larage propposal image). This leads to  ugly cropped images and might also be the 
reasy why the users reupload images alot (we  have 1 Gigabyte images/images scales in the database).
