### ISSUE TITLE
Generell Questions

### ISSUE THREAD

**Issue by TuningGuide** [liqd/adhocracy3#1861]
- Is the Documentation at https://adhocracy-3-playground.readthedocs.org/en/latest/index.html still valid?
- Is there any testbed / demo site where adhocracy 3 is running on?

**Comment by xi** [comment]
Hi!

The current docs are at https://adhocracy3.readthedocs.org/en/latest/index.html.

There is no public demo installation, but you can see it running at https://advocate-europe.eu/en/idea-space.

Hope that helps!

**Comment by TuningGuide** [comment]
That was quick ^^, thx
