### ISSUE TITLE
Newly created proposals have creator 'null'

### ISSUE THREAD

**Issue by dwt** [liqd/adhocracy3#1887]
The ui maps that to 'guest'.

We can reproduce this on S1 after a today's merge of master:
* bin/buildout -c buildout-s1.cfg
* open s1
* login as god/password
* create proposal
* check proposal creator

Probably also happens in other environments - but I couldn't check that yet.

**Comment by dwt** [comment]
sorry, I should be more specific. The proposal has the correct creator, but the first version (000000) has the creator 'null'.

**Comment by xi** [comment]
This could be related to #1735

**Comment by pallix** [comment]
@joka did you have a look?

**Comment by joka** [comment]
@nidico to merge the fix we need to merge https://github.com/liqd/adhocracy3/pull/1896 first.
Can you have a look at this?
