### ISSUE TITLE
user images visible on mein berlin staging

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy3#1903]
we updated meinberlin staging and realized that the user images are visiblie (for example here: https://embed-meinberlin-stage.liqd.net/r/alexanderplatz/workshopverfahren-2015/@proposals). I thought the are switched off by default?

**Comment by xi** [comment]
It was intentional that this feature is enabled by default. liqd's designs are not yet adapted so we have to disable it for all platforms. But that is an issue of our deployment, not of the software itself.

**Comment by MagdaN** [comment]
I would like to discuss this with the PO

**Comment by nidico** [comment]
No, this is a bug, we indeed switched off (or intended to switch off) profile images off by default.

**Comment by nidico** [comment]
We have discussed this with @rukala. In general, this feature should be switched on (as we want to use it from January / February on), but it should be turned off on all platforms.

In 4722cadc134a13074d38fab731744847816826e8, the feature was only switched off in the buildout config. I now switched it off in all deployment salt configs as well.
