### ISSUE TITLE
Simple API-CHANGES to improve performance

### ISSUE THREAD

**Issue by joka** [liqd/adhocracy3#1932]
The follwoing proposals work without changing the frontend and are easy in 
the backend. They are meant as workarounds until we have a proper REST-API concept,
                                                   
1. needless frontend requests with huge performance impact:
                                                   
- /principals/users                                
- ../process/assets                                                                                         
- ../process/proposal/version/rates                
- ../process/proposal/version/comments             
- ../process/proposal/version/assets               
- ../process/proposal/version/badge_assignments    
                                                   
Proposal:                                          
                                                   
a) remove these resources from listing sheet.pool.IPool:elements (works except for /principal/users)
b) reduce response size: return search result with query parameter 'elements=omit' and 'count=True'.
                                                   
2. needless sheet fields with huge performance impact:
                                                   
- ..sheets.rate.IRateable:rates                    
- ..sheets.comment.ICommentable:comments           
- (..sheets.version.IVersionable:following, no big impact, but also needless)
                                                   
Proposa

c): remove these fields

**Comment by pallix** [comment]
Can we close this? Everything has been implemented or?

**Comment by xi** [comment]
+1. We should wait until #2020 is merged though.

**Comment by pallix** [comment]
It's merged. Congrats!
