### ISSUE TITLE
Owner cannot PUT on his own proposal

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy3#1933]
in AE, when I create a proposal that is not admin and then make an OPTIONS request on that proposal with the owner being logged in I am only allowed to GET (at least that is, what OPTIONS tells me)

**Comment by pallix** [comment]
I cannot reproduce it on staging. Do you still have the problem?

**Comment by pallix** [comment]
Closing this as we saw with Magda that the backend result are indeed correct.
