### ISSUE TITLE
Name conflicts when creating proposals

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3#1943]
When creating a proposal for mercator 2015, I get a name conflict for the proposal name:

http://localhost:6551/r/mercator/proposal_0000000_2016-01-06T10:27:53.859694+00:00/VERSION_0000000/

**Comment by pallix** [comment]
I could reproduce it only once

**Comment by pallix** [comment]
Related to #1738

**Comment by joka** [comment]
I have no idea how this happend.
Is there anyway to reproduce this?

**Comment by pallix** [comment]
maybe `change_pools_autonaming_scheme` and/or `move_autoname_last_counters_to_attributes` should be reexecuted (if they will not conflict when reexecuting) ? I think we add a bug in the first one and maybe it was never executed properly on Advocate Europe

**Comment by 2e2a** [comment]
Hard to reproduce or understand what went wrong on the installation.

Closing it now and will look into it, if it occurs again.
