### ISSUE TITLE
As winner of Advocate Europe 2015 I can't edit my proposal name, pictures and URL of my website

### ISSUE THREAD

**Issue by rukala** [liqd/adhocracy3#1944]
As winner of Advocate Europe 2015 I can't edit my proposal name, picture and URL of my website when the process is in "winners" phase.

Maybe this is due to the fact that the process should be in "realisation" phase on productive now?

**Comment by pallix** [comment]
This was modelled like this for the "result" phase. I will change the permissions.

**Comment by fredewe** [comment]
> Am 06.01.2016 um 12:02 schrieb rukala <notifications@github.com>:
> 
> As winner of Advocate Europe 2015 I can't edit my proposal name, picture and URL of my website when the process is in "winners" phase.
> 
> Maybe this is due to the fact that the process should be in "realisation" phase on productive now
> 
> 
It should be in „realisation“ phase now.

**Comment by pallix** [comment]
We will probably have other bugs if editing a proposal version during the 'result' phase, like the 'winner' badge disappearing.

@xi says there is an issue referencing this problem I cannot find it.

**Comment by pallix** [comment]
It should work now. Reopen if problem reappear.
