### ISSUE TITLE
No comments in AE

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy3#1956]
I just realized that the comments in AE2015 are not shown anymore - the comment column stays white. There is an error message in my browser debugger - it says: TypeError: Cannot read property 'replace' of null     at e.getOrSetCached (Adhocracy.min.js?_=1452175557:1)

**Comment by xi** [comment]
> TypeError: Cannot read property 'replace' of null at e.getOrSetCached

This usually happens if we try to make a request with an empty path. I will investigate where this is triggered.

**Comment by xi** [comment]
This is a backend issue: The LAST tag on comments is `null` (e.g. https://frontend.advocate-europe.eu/api/mercator/Localization_ofthebestEuropeanMOOCsforUkrainians483/introduction/comments/comment_0000005/)

**Comment by joka** [comment]
> This is a backend issue: The LAST tag on comments is null (e.g. https://frontend.advocate-europe.eu/api/mercator/Localization_ofthebestEuropeanMOOCsforUkrainians483/introduction/comments/comment_0000005/)

The migration failed on production and the bin/sd_evolve script is broken now.
I guess this is due to database conflicts while migrating.

@2e2a I tested the migraion on staging, but we should sllways double check if the migration passes, if not undo and restore databse.

**Comment by joka** [comment]
I did not manage to run the migration scripts due to various BTree errors (basic data structure) on productive.
This is not reproducable on staging!  So we need we need a "staging" installation on the productive server to debug this.

**Comment by joka** [comment]
Maybe this is related to Updating Btrees to 4.2.0, but I cannot test this since i cannot build adhocracy with my account. Can someone gib me a tmux or screen session?

**Comment by pallix** [comment]
@joka I sent you an email

**Comment by joka** [comment]
I added a test installation to play around 'adhocracy3_test'  on arendt. 
Downgrading Btrees to 4.1.3 did not help, to reproduce just run bin/sd_evolve --lastest

One migration step passed now, but important one for this issue is still left.
I`m going to debug with the productive database on my local machine.

**Comment by joka** [comment]
Auf productive with die python version von BTrees benutzt 
Auf staging die CExtension, wie es sein soll

**Comment by joka** [comment]
> Auf productive with die python version von BTrees benutzt 
> Auf staging die CExtension, wie es sein soll

Grund ist falsche libc Version:

----> 1 from BTrees._OOBTree import OOBucket

ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/advocateeurope-adhocracy3-prod/adhocracy3/lib/python3.4/site-packages/BTrees/_OOBTree.cpython-34m.so)

**Comment by joka** [comment]
@slomo any Idee how to fix this?  This may cause serious damage in our database.

**Comment by joka** [comment]
Mercator is up to date now.
