### ISSUE TITLE
Mercator 2015 winner lists broken on staging

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3#1964]
We cannot see the winners of Advocate Europe 2015 on staging.

**Comment by xi** [comment]
Can you please add a link that reproduces the proplem?

**Comment by pallix** [comment]
Sure:

https://plone-a3-stage.liqd.net/en/idea-space#!/r/mercator/

No proposals listed, clicking "winners" also doesn't show anything.

**Comment by pallix** [comment]
The URL is `https://plone-a3-stage.liqd.net/en/winners`. It's still broken. The german version works: `https://plone-a3-stage.liqd.net/de/winners`

**Comment by xi** [comment]
`.adhocracy_marker_3` is missing on that page. That's an issue in plone.

**Comment by xi** [comment]
Fixed (the phases had not been published)
