### ISSUE TITLE
New "home" concept

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3#1965]
_This may not fit well as a github issue. Feel free to transfer this to some other place._

Most classic websites have a home page that can always be reached by clicking on the logo or title in the top left of the screen ([1. good deed in web design](https://www.nngroup.com/articles/ten-good-deeds-in-web-design/)). This way it is ensured that users can always go back to a familiar place in case they get lost.

In adhocracy, we have a variation of that where each space has its own home page. You can get there using the space switcher. In addition, the user is sometimes redirected to `/` which in turn redirects to a hardcoded location.

As with many things in adhocracy, this is half-baked and too complicated (see e.g. https://github.com/liqd/adhocracy3/issues/1640). In an effort to make things better we want to remove the space concept. The question is: How will it be replaced? This is what we came up with after some discussion:                

As said before, you usually reach home by clicking on the logo in the top left of the screen. In our case, this space is occupied by the embedding CMS. So that CMS is in charge of providing a home button. However, adhocracy can optionally provide its own home button to make embedding as simple as possible. 

For the case of redirecting to `/`, the following locations are used in decreasing preference:
-   `initialUrl` (plain/context embeds)
-   process (on single process setups)
-   process overview
-   If none if these is available, we have a problem.

Tasks
-   [x] remove space switch
-   [x] remove space concept
-   [x] add optional home button
-   [ ] change `/` redirection logic
-   [X] implement process overview
-   [x] define single process setups

**Comment by pallix** [comment]
Do we need to distinguish between:

process (on single process setups)
and
process overview (= organisation containing processes, no?)

since both are contained in an organisation?

**Comment by xi** [comment]
Consider the following case: If a platform only contains one process, there are two candidates for home: `/organisation/process/` (process) and `/organisation/` (process overview). If the platform is considered a "single process setup", the process should be used directly. Otherwise, the process overview should be used.

**Comment by der-john** [comment]
This is as good as it will get.
