### ISSUE TITLE
User detail page

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy3#1971]
on the user page it says:

* {name}'s proposals
* proposals of user are not shown

**Comment by xi** [comment]
> {name}'s proposals

That's an issue.

> proposals of user are not shown

I assume that you checked this in mercator2016. Unfortunately, This does only list mercator2015 proposals in mercator. I talked to @stadine an we agreed to remove the proposal list from user profiles in mercator for now.

**Comment by xi** [comment]
Has been fixed by removing the proposal list
