### ISSUE TITLE
403 response on assets in protected process

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3#1973]
If a process is in draft state and the creator wants to create some content that contains an image, the image can not be displayed (403 forbidden). The reason is that the request is not triggered by JavaScript but by a `<img>` element, so the authentication headers are missing.

**Comment by joka** [comment]
Possible solutions:

1. disable permission check for Image scales

2.  disable permission check for Image scales but hide by obscurity (make random string part of the URL, like for users) 

3. find a javascript solution 

i'm in favour of 2.

**Comment by pallix** [comment]
Why choose solution 2? Why should be images different from other resources?

**Comment by joka** [comment]
> Why choose solution 2? Why should be images different from other resources?

- image scales are cached forevere in the browser (unlike other resources)

- get request is not triggered by JavaScript but by a <img> element, so the authentication headers are missing.
