### ISSUE TITLE
html5 audio in chrome / chromium

### ISSUE THREAD

**Issue by fisx** [liqd/adhocracy3#1977]
`<audio src="...>` does not play; the control behaves like the audio is invalid.  firefox works fine.

Observed in the registration widget with captchas enabled.  Follow #1950 on how to reproduce this.  

@MagdaN: should I add any more details here, or can you work with this?

**Comment by xi** [comment]
Which audio format are you using? Note that not all browsers support all audio formats (see [mdn: supported media formats](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats)). If this is the problem, consider using the `<source>` element to provide more than one format.

**Comment by fisx** [comment]
> Which audio format are you using? Note that not all browsers support all audio formats (see [mdn: supported media formats](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats)). If this is the problem, consider using the `<source>` element to provide more than one format.

thanks for the link, very useful.  we are using wav data and content type audio/l16.  that's probably what we should change.

i wonder if we should deliver ogg instead or just change the content type?
