### ISSUE TITLE
mercator2..extrainfo should be optional

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3#1986]
When I try to submit a mercator2016 proposal without extrainfo I get the following error message:

```
{
  description: "Required",
  location: "body",
  name: "data.adhocracy_mercator.sheets.mercator2.IExtraInfo.extrainfo"
}
```

I am especially confused because the meta_api reports this field as `create_mandatory: false`.

**Comment by xi** [comment]
Frontend has already been fixed in #1987

**Comment by pallix** [comment]
I think there is no backend problem here. 

Extrainfo is a reference in the  `sheets.mercator2.IMercatorSubResources` and is not optional. 

What is optional is to post an extrainfo subresources with a `adhocracy_mercator.sheets.mercator2.IExtraInfo` a sheet.

Does that make sense?

**Comment by xi** [comment]
How can I remove that sheet?

**Comment by local-girl** [comment]
Any update on this ? This field needs to be optional

**Comment by pallix** [comment]
Ok i think I understand better and tried to fix by #2004.

Can you retry?

**Comment by local-girl** [comment]
I still get the required error
```
description: "Required"
name: "data.adhocracy_mercator.sheets.mercator2.IExtraInfo.extrainfo"
```

**Comment by pallix** [comment]
It was an environment problem, it's working now.
