### ISSUE TITLE
comments_count broken

### ISSUE THREAD

**Issue by Johnschmidfront** [liqd/adhocracy3#2055]
- The comment count displayed under the speechbubble isn't updated directly after creating/ deleting comments - I need to refresh to update it.
- If I delete 1 comment with 1 reply, comment count currently gets -1, but it should get -2.

**Comment by xi** [comment]
> The comment count displayed under the speechbubble isn't updated directly after creating/ deleting comments - I need to refresh to update it.

Duplicate of #410

> If I delete 1 comment with 1 reply, comment count currently gets -1, but it should get -2.

Duplicate of #549
