### ISSUE TITLE
Unnecessary registry feature on some functional tests

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3#2081]
Some of the functional tests have an unnecessary `registry` feature. It was to avoid an error when doing `transaction.commit`, it didn't get the good registry.

Tests should be refactor to do something like that:
```
json_file = str(datadir.join('resources.json'))
manager.push({'registry': app_admin.app_router.registry})
add_resource(...
```  
These function calls should be abstract in a function since a lot of tests do them. 

See also:
https://github.com/Pylons/pyramid/blob/master/pyramid/router.py#L183
http://docs.pylonsproject.org/projects/pyramid/en/latest/api/testing.html#pyramid.testing.setUp

**Comment by joka** [comment]
fixed with #2121

**Comment by joka** [comment]
IF 

> Tests should be refactor to do something like that:
> 
> json_file = str(datadir.join('resources.json'))
> manager.push({'registry': app_admin.app_router.registry})
> add_resource(...
> These function calls should be abstract in a function since a lot of tests do them.

We now have helper functions

**Comment by pallix** [comment]
We can try ; I think there was a reason (circular imports?) why I put them in a separate modules but I forgot exactly which.

**Comment by pallix** [comment]
This has been fixed, as stated above by Joscha.
