### ISSUE TITLE
Remove Anonymous Role

### ISSUE THREAD

**Issue by joka** [liqd/adhocracy3#2084]
**motivation:**

We are refactoring the authentication policy and are creating alot of new workflows. If we want to change somethig regarding the authentication system we should  do it now.

Currently the following roles are automatically applied by the authentication policy:

- Everybody (authenticated/not authenticated users)
- Anonymous (not authenticated users)
- Authenticated (authenticated users)

Everybody and Authenticated is part of the pyramid authentication policy specification. We added Anonymous because its easy to understand and simplifies allowing something for not authenticated but disallow it for authenticated users.

The downside is we cannot use another pyramid authentication policy without modifications (For example to  integrate thentos in a proper way we should use the RemoteAuthenticationPolicy) and we have  more complexity.

**Proposal**:

- Remove Anonymous Role and use Everybody instead.

**Deliverables**:

- rm Anonymous Role
- use Everybody instead of Anoymous in Role/Permission mappings
- Make sure the bplan workflow to disallows authenticated users to create proposals (there are already tests)
- update documentation

**Comment by xi** [comment]
I cannot say anything about the impact on the backend. But the frontend does not have a concept of roles, so there should be no issues from this side.

**Comment by joka** [comment]
fixed with #2166
