### ISSUE TITLE
Wrong error (or no error) in registration dialogue

### ISSUE THREAD

**Issue by rukala** [liqd/adhocracy3#2100]
When I register on https://a3-opin-stage.liqd.net/register the email address field was highlighted red even though I entered a correct email address.

**Comment by xi** [comment]
Can you please send me a mail with the email address you used?

**Comment by xi** [comment]
Works for me. Can you give more context? Which browser? What did you do before? What addresses do work, which ones don't?

**Comment by xi** [comment]
Closing because this could not be reproduced.
