### ISSUE TITLE
Strange autonaming behavior on Advocate Europe

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3#2101]
The autonaming counter of the users pool on AE seems to have been resetted. For example this user was created in 2015:

https://frontend.advocate-europe.eu/api/principals/users/0000028/

and this one in 2016:

https://frontend.advocate-europe.eu/api/principals/users/0000028_2016-01-05T15%3A21%3A39.696445%2B00%3A00/

but they both get the same prefix in their name.

**Comment by xi** [comment]
Related to #1738

**Comment by 2e2a** [comment]
Hard to reproduce or understand what went wrong on the installation.

Closing it now and will look into it, if it occurs again.
