### ISSUE TITLE
styleguide script location and generation

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3#2118]
Is it okay for the `bin/all_styleguides` script to be directly in `bin`? all other scripts are generated from builtout.

**Comment by xi** [comment]
The proper place would probably be `src/adhocracy_frontend/adhocracy_frontend/scripts/`, but that's so damn annoying.

**Comment by pallix** [comment]
The place is good but other scripts are generated from buildout, this one is not. I'm wondering if this is problematic or not.

**Comment by joka** [comment]
> The place is good but other scripts are generated from buildout, this one is not. I'm wondering if this is problematic or not.

yes, buildout expect that everything in 'bin' is created with buildout and we should not brake this.

We could use setuptools to create the script (see examples in adhocracy_frontend.setup.py).
But  its very deploy specific, so i would just create it with buildout (adhocracracy_frontend.checkcode_and_compile.cfg)
