### ISSUE TITLE
only show chapter jump navigation if we have more than one chapter

### ISSUE THREAD

**Issue by stadine** [liqd/adhocracy3#2140]
As a user I only want to choose a chapter if I can choose different chapters. 

Here's an example:
https://opin.me/en/projects/commenting-texts-testgroup/#!r/test/collaborative_text/

@xi you can delete the issue if it's not a feature request.

**Comment by xi** [comment]
What exactly do you mean by "choose a chapter"? Is it about the navigation on the left?

**Comment by stadine** [comment]
jap

**Comment by Johnschmidfront** [comment]
I just noticed that the issue still exists in the collaborative_text process.

**Comment by Johnschmidfront** [comment]
nope, turns out I just hadn't compiled scss yet.
