### ISSUE TITLE
Accessing private processes without authorization returns 403 instead of 401 error

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3#2144]
When accessing a private processes without authorization the backend returns a 403 error instead of 401 error.

**Comment by xi** [comment]
Maybe related to #277?

**Comment by joka** [comment]
> Maybe related to #277?

403 ist the right response according to wikipedia https://en.wikipedia.org/wiki/HTTP_403  and the less wrong response according to the rfc: https://github.com/liqd/adhocracy3/issues/277#issuecomment-67330985. Thats why we closed #277.

Can you describe what exactly the frontend wants do difference? 

ping @MagdaN @slomo

**Comment by MagdaN** [comment]
Its for the private processes, there are two cases:

1) user can't access the process, because she is not logged in (401)
2) logged in user can't access the process because she is not allowed the see the process (403)

**Comment by joka** [comment]
> 1) user can't access the process, because she is not logged in (401)

> 2) logged in user can't access the process because she is not allowed the see the process (403)

apart from the general problems with the defintion of 401/403,  we cannot say if the user can`t acess a resource because she is not logged in. This depends on what local roles her user group has for the wanted resource.

Possible workarounds with 403 responses:

1.  add general view permission informations to 403 responses:

       - json data with information what are the user roles and what roles have view permissions for the wanted resource
       - works for get request only (for put/post requests are many permissions are involved)
       - works for all resources

2. mark process workflow as "private"

       - frontend has to lookup the workflow metadata and decide what to tell the user
       - works for process only
       - easy to implement in the backend

more ideas?

**Comment by MagdaN** [comment]
I added a PR (https://github.com/liqd/adhocracy3/pull/2151) to deal with it in the FE, feel free to discuss about it - let me know what your decission is.

**Comment by joka** [comment]
> I added a PR (#2151) to deal with it in the FE, feel free to discuss about it - let me know what your decission is.

Ok, who from the frontend team wants to work on this issue then?

**Comment by joka** [comment]
We have a frontend solution now, can we close this ticket?

**Comment by xi** [comment]
The frontend solution is not merged. Also, this is still an issue in the backend, even though there is a workaround in the frontend.

**Comment by slomo** [comment]
Frontend solution is now merged. Are there plans to fix this in the backend? Otherwise we might as well close this issue (not my favoured solution).

**Comment by xi** [comment]
It is not clear whether this is actually wrong. Also, the frontend has a effective workaround. Closing.
