### ISSUE TITLE
Alexanderplatz: new proposal isn't posted

### ISSUE THREAD

**Issue by der-john** [liqd/adhocracy3#2146]
I've built a local Alexanderplatz copy and set the workflow state to `participate`, opened `r/organisation/alexanderplatz` and logged in as god. I click on "Create Proposal" and fill in `title` and `description` and then submit.

I would then expect to see the proposal detail view with the new `title` and `description`.

Instead, I see the proposal detail view, but `title` and `description` are empty. I get an error in the console:

> TypeError: Cannot read property 'coordinates' of undefined
    at Proposal.ts:125
    at processQueue (angular.js:14792)
    at angular.js:14808
    at Scope.$eval (angular.js:16052)
    at Scope.$digest (angular.js:15870)
    at Scope.$apply (angular.js:16160)
    at done (angular.js:10589)
    at completeRequest (angular.js:10787)
    at XMLHttpRequest.requestLoaded (angular.js:10728)

When I navigate back to the proposal list, the new proposal isn't listed, also not after reaccessing the page. 

(Only workaround: edit the proposal directly after creating it.)

**Comment by xi** [comment]
I can verify this is still an issue. The reason seems to be that the `adhocracy_core.sheets.geo.IPoint` sheet is missing from the resource returnes by the API. This also happens when the sheet is included in the POST. I can also verify that editing the proposal fixes the issue.

Tested as god in participate state.

**Comment by der-john** [comment]
Today, when testing Alexanderplatz, this issue was still there. Only difference: editing the proposal didn't help.

**Comment by xi** [comment]
Seems to have been fixed.
