### ISSUE TITLE
Session gets deleted when trying to access a private process

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3#2160]
See #2151 for previous discussion.

When I try to access a private process created from `src/adhocracy_euth/adhocracy_euth/workflows/test_public_private_process/private.json` with a logged-in, non-god user, I get the expected result. However, when I reload, my session is not valid anymore.

If I try the same with a public process in draft state I get the correct result: The session is still valid.

**Comment by xi** [comment]
May be a duplicate of #1371

**Comment by Johnschmidfront** [comment]
I'm trying to reproduce this, but I get the error:
> 403 - Du hast nicht die Berechtigung, diese Ressource anzusehen.

**Comment by xi** [comment]
That is exactly the point. As god you should have access.

**Comment by 2e2a** [comment]
The reload problem seems to be fixed.

The god access problem will be solved by #2726

**Comment by xi** [comment]
I am not completely sure whether this has been properly fixed. It might just be a side effect of the workaround we implemented for #2263.

**Comment by 2e2a** [comment]
> I am not completely sure whether this has been properly fixed. It might just be a side effect of the workaround we implemented for #2263.

After disabling the workaround the private process still works.
So this seems to be fixed independent from the workaround
