### ISSUE TITLE
comment count on meiberlin includes all versions of edited comments

### ISSUE THREAD

**Issue by 2e2a** [liqd/adhocracy3#2188]

**Comment by joka** [comment]
This would not be the case if propsoal item instead of proposal version are commentable.
As long as we don't do this change we have to fix resources.subsriber.update_comment_count.
It should only  increase if the added comment has the 'FIRST' tag.

**Comment by slomo** [comment]
This is an issue that blocks the release of the platform. How should we deal with it? Ideal would be a work around or solution until the 1st of april.

**Comment by pallix** [comment]
Closed by #2200
