### ISSUE TITLE
Comment listing not updating on navigation

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3#2205]
See https://advocate-europe.eu/en/idea-space#!/r/advocate-europe/2016/proposal_0000669/@comments:pitch

- **what I did**: Navigate to one proposal; Navigate to the comments of one section; Without closing the comment column, navigate to the comments of another section.
- **expected result**: I see the comments of the second section.
- **what actually happens**: I still see the comments of the first section.

I guess this happens bacause the comment listing does not watch its `path` parameter.

**Comment by Johnschmidfront** [comment]
Fascinating: The same thing happened to me in Mercator2016, but not in spd...

**Comment by Johnschmidfront** [comment]
I'm a little confused: in `Listing.ts`, there is a piece of code that kind-of makes the listing watch its path:

line 302-322:
```
$scope.$watch("path", (newPath : string) => {
                    unregisterWebsocket($scope);

                    if (newPath) {
                        // NOTE: Ideally we would like to first subscribe to
                        // websocket messages and only then get the resource in
                        // order to not miss any messages in between. But in
                        // order to subscribe we already need the resource. So
                        // that is not possible.
                        $scope.update().then(() => {
                            try {
                                $scope.wsOff = adhWebSocket.register($scope.poolPath, () => $scope.update());
                            } catch (e) {
                                console.log(e);
                                console.log("Will continue on resource " + $scope.poolPath + " without server bind.");
                            }
                        });
                    } else {
                        $scope.clear();
                    }
                });
```

**Comment by der-john** [comment]
So I had another unsuccessful try at this issue, but at least I think I see a problem:
> I guess this happens bacause the comment listing does not watch its path parameter.
I have the feeling that it DOES watch its path parameter. But clicking on a comment button doesn't change the path in the URL, it just changes the view (e.g.@comments:pitch). Meanwhile, the backend really does need the path of the `SIMercatorSubResource` to fetch the comments, because that is where the `/comments` pool is located.
