### ISSUE TITLE
Separate Like and Vote concepts

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3#2208]
The concepts for voting and supporting proposals are not clearly separated on the backend and on the frontend.

A part of the work has been done on #1855 but not be finished.

**Comment by xi** [comment]
I am not sure which of these options is meant here?

- Like (only positive) vs. Rate (positive and negative)
- Have more than one distinct rating/liking options on a single resource

**Comment by xi** [comment]
Closing due to ambiguity
