### ISSUE TITLE
mein.berlin.de: Stadtforum process isn't displayed on its detail page.

### ISSUE THREAD

**Issue by Johnschmidfront** [liqd/adhocracy3#2215]
See e.g. https://meinberlin-stage.liqd.net/w/prozesse/gelingt-die-inklusion-in-berlins-schulen/#!r/familienportal/dialog/poll_0000001/VERSION_0000001/

**what I did**: Click on a Stadtforum process.
**expected result**: See the header ("Stadtforum") and an iframe containing the Stadtforum process.
**what actually happens**: I see only the header ("Stadtforum"); no errors.

**Comment by Johnschmidfront** [comment]
I think the embed code is wrong. Therefore, this is a meinberlin-wagtail issue.

**Comment by Johnschmidfront** [comment]
I just confirmed my idea with a local test. I'm opening a meinberlin-wagtail issue.

**Comment by xi** [comment]
https://github.com/liqd/meinberlin-wagtail/issues/24
