### ISSUE TITLE
inconsistent behavior when logged in as god

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3#2220]
I created a buergerhaushalt process without changing the workflow state (default: draft) and logged in as god.

After creating a proposal the `adhocracy_core.sheets.versions.IVersions` sheet was empty which lead to an error. After I changed the workflow state to participate the sheet contained the right versions.

The god user should not be affected by permission checks. So the workflow state should not influence anything (except the workflow state) in the API.

**Comment by pallix** [comment]
Buergerhaushalt uses the standard workflow, where Everyone has Deny for view permission in the draft state.

I think the problem may be that god is Everyone, like everyone, and the ALL_PERMISSIONS permissions is set only on the root object and not on the process, so Deny will match first.

**Comment by pallix** [comment]
@joka honestly we could set ALL_PERMISSIONS for god when settings the ACL on the resource but it will probably break somewhere else another time (?). Maybe we can REALLY cut all permissions checks for god in the `permits()` function and always returns true when the principal is god

**Comment by pallix** [comment]
@joka means `versions` comes from the search and permissions should not be checked for god there.

**Comment by joka** [comment]
We can add a hack to disable permission checks for searches/references. But I wonder why we use the god account after all, this is a potential security issue. For testing we can also use a "real" user like a user with admin role.

**Comment by xi** [comment]
> But I wonder why we use the god account after all

I use it because it is the only account that is created automatically, i.e. I do not want to go through the register flow each time I work with a new database.

**Comment by pallix** [comment]
So the solution would be to create a user with role 'participant' (and a short name) when a3 is runned for development?

**Comment by joka** [comment]
> So the solution would be to create a user with role 'participant' (and a short name) when a3 is runned for development?

for development we dont have to create it manually, the config option "adhocracy.add_test_users" creates a test user for every user role, for passwords/login see adhocracy_core.testing.py

regarding the god user I propose:

- add admin role instead of enabling ignore permission 
   for security reasons (we don't want a user account that bypass the permission system, for example admin may not change user votes )
 
- rename to admin
    to reflect his role, also some people don't like talking about "god"
