### ISSUE TITLE
meinberlin build broken: processes aren't loaded correctly

### ISSUE THREAD

**Issue by Johnschmidfront** [liqd/adhocracy3#2235]
This issue has happened since @2e2a 's A3 release today (the release before that was last week):

1. I visit https://meinberlin-stage.liqd.net/.
I click on any Stadtforum or Kiezkasse process tile.
The browser starts loading the page, doesn't stop and...

gives an error...
> angular.min.js?_=1460981742:107 Illegal use of inject directive in the template! No parent directive found that requires a transclusion. <adh-inject data-transclusion-id="menu">

... and produces non-stop error messages saying:
> angular.min.js?_=1460981742:107 Error: [ngTransclude:orphan] http://errors.angularjs.org/1.4.8/ngTransclude/orphan?p0=%3Cdivlass%3D%22l-cell-inner%22%20data-ng-transclude%3D%22%22%3E

2. I visit https://meinberlin-stage.liqd.net/.
I click on the EPPTF or EngagementLandschaft process tile.
The browser starts loads a very incomplete iframe, which only displays two small icons and the text:

> Beteiligung nicht möglich

**Comment by 2e2a** [comment]
It was a broken build. Cleaning the build environment and rebuilding solved the issue.
