### ISSUE TITLE
Readthedocs outdated

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3#2243]
The documentation on readthedocs is outdated. Apparently readthedocs thinks that [2016-02-jk-imperia-api-documentation is the latest version](https://readthedocs.org/projects/adhocracy3/versions/).

@joka, I think you are the only one with sufficient persissions to change that. Could you please also grant the permission to some others?

**Comment by 2e2a** [comment]
Explicitly setting the branch to master in readthedocs fixed the issue.
