### ISSUE TITLE
Duplicate information in workflow-assignment state-data

### ISSUE THREAD

**Issue by 2e2a** [liqd/adhocracy3#2256]
We currently have start_date and end_date for each state in the WorflowAssignment state_data.
This is duplicate and we would need to check constancy, i.e. end of a state is equal to start of the next.

I would suggest to remove end_date.

This should be considered in the workflow auto-transition script.

**Comment by joka** [comment]
thats right, adding the end_date was neeed by the frontend, but it doent make sense for the workflow state machine. 
@xi can we remove the end_date and make the frontend use the next state start_date instead?

**Comment by xi** [comment]
Interestingly, I could not find any place where `end_date` is really used in the frontend. So yes, you can remove it. Still some places need to be adapted that you can find with a simple `git grep end_date`.

**Comment by 2e2a** [comment]
Fixed by #2258
