### ISSUE TITLE
Missing description sheet during migration

### ISSUE THREAD

**Issue by slomo** [liqd/adhocracy3#2261]
After migration from 0.3.10 to 0.4.18 the IDescriptionSheet is missing. See [1](https://spd-stage.liqd.net/api/digital_leben/).

**Comment by joka** [comment]
It seems a migration is missing somehow, can you rerun add_description_sheet_to_organisations and add_description_sheet_to_process?

**Comment by slomo** [comment]
```
# bin/sd_evolve --mark-unfinished adhocracy_core.evolution.add_description_sheet_to_organisations etc/backend.ini
# bin/sd_evolve --mark-unfinished adhocracy_core.evolution.add_description_sheet_to_process  etc/backend.ini
# bin/sd_evolve --latest etc/backend.ini
```

The process now has still the same issue, but the root organisation has some other issue. During deployment all migrations where finished successfully.

**Comment by joka** [comment]
The search command used by the mirgration script does not return digital_leben. 
It looks like the interfaces index for this resource is broken. I suggest we do manual migration ( `zope.interface.declarations.alsoProvides(<digital_leben>, IDescription)` ) for now and debug this next week.

**Comment by 2e2a** [comment]
This was fixed manually in this installation and did not occur on other installation since a while.

Closing this. Will create a new issue, if the problem reoccurs.
