### ISSUE TITLE
adhResourceAction.resourceWidgetDelete does not work

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3#2268]
We currently have 2 places where the delete resource action is used:

-  mercator2015 proposal
-  mercator2016 proposal

Unfortunately, this action only works with resourceWidgets. We decided to deprecate resourceWidgets in #1711 and converted comments in #1743. mercator2016 was added in #1863 and has never been a resourceWidget. So basically deletion is broken with these two.

**Comment by der-john** [comment]
this seems not to be up-to-date:
comment.ts uses adhHttp.hide(). I tried it out in a Kiezkasse and it worked fine.

**Comment by der-john** [comment]
the directive has been renamed in #2428.

**Comment by der-john** [comment]
it works fine in Mercator2015 and is not used in Mercator2016.
