### ISSUE TITLE
Image upload in Euth is broken

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy3#2273]
BE Error 400: "Claimed MIME type is image/jpeg but file content seems to be application/octet-stream"

**Comment by MagdaN** [comment]
Reset button also does not work (no error in chrome debugging console)

**Comment by joka** [comment]
Can you add the image that is causing this error, or does this error always occure?

**Comment by MagdaN** [comment]
The error always occurs

**Comment by joka** [comment]
I cannot test it locally, build error: src/euth/euth/build/js/AdhocracySpec.ts(19,22): error TS2307: Cannot find module './Packages/LocalSocket/LocalSocketSpec'.
The acceptance test on master were passing yesterday,   maybe this is a deployment issue, is https://github.com/ahupp/python-magic isntalled and working properly (@slomo) ?

**Comment by MagdaN** [comment]
The problem occurs on my local machine

**Comment by joka** [comment]
> The problem occurs on my local machine
Your are using MacOs or? please check that the dependencies for python-magic are installed https://github.com/ahupp/python-magic and  that `import magic` works. 

We should  add installation instructions for MacOs to the docs.

**Comment by joka** [comment]
Do the acceptance test pass on your machine?

**Comment by MagdaN** [comment]
Installing libmagic fixed the problem

**Comment by joka** [comment]
Can you check that the installation instructions cover this?

**Comment by joka** [comment]
Also if libmagic is a hard dependency the backend should raise an exception

**Comment by slomo** [comment]
I added a pull-request for please review it.
