### ISSUE TITLE
IGeoProposalVersion gets converted to IProposalVersion

### ISSUE THREAD

**Issue by der-john** [liqd/adhocracy3#2317]
I am trying to get the `adhocracy_meinberlin.resources.idea_collection.IProcess` running locally by setting up the IdeaCollection workbench for it.

On the @create_proposal view, I provide title, description and a point, and click on submit.

The request header reads as follows (excerpt):
>1 {method: "POST", path: "@pn15",…}
body {content_type: "adhocracy_core.resources.proposal.IGeoProposalVersion",…}

The response preview reads as follows (excerpt):
> 1 {code: 200,…}
body: {path: "http://localhost:6541/organisation/idea_collection2/proposal_0000002/VERSION_0000000/",…}
content_type: "adhocracy_core.resources.proposal.IProposalVersion"

I am with my Latin at the end.

**Comment by joka** [comment]
mmh,  i guess we had a similar problem in the past, I'll have a look.
Meanwhile: I cannot build meinberlin: 

Installing resources.
resources: Running '. /home/joka/dev/adhocracy-3/source_env
git ls-files --other src/meinberlin/meinberlin/build/js/Resources_ | xargs rm -f
/home/joka/dev/adhocracy-3/bin/tsc --module commonjs --pretty src/meinberlin/meinberlin/build/js/mkResources.ts
/home/joka/dev/adhocracy-3/bin/node src/meinberlin/meinberlin/build/js/mkResources.js src/meinberlin/meinberlin/build/meta_api.json src/meinberlin/meinberlin/build/js'
Unused options for resources: 'update-command'.
Installing javascript.
javascript: Running '/home/joka/dev/adhocracy-3/bin/node /home/joka/dev/adhocracy-3/bin/tsc -m umd --sourcemap --pretty src/meinberlin/meinberlin/build/js/Adhocracy*.ts'

1 /// <reference path="../../../lib/DefinitelyTyped/jasmine/jasmine.d.ts" />
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I already tried removing .installed.cfg and rerun buildout, do you have any other suggestion?

**Comment by joka** [comment]
> I already tried removing .installed.cfg and rerun buildout, do you have any other suggestion?

I run buildout with option `-N` (don't look for new dependecy versions) maby that was the reason.
Without the bower dependencies are updated again, but I cannot proceed due to missing connection to  
git://github.com/nidico/socialshareprivacy.git#392c61fef7

**Comment by joka** [comment]
buildout out passed, but same problem again :(

**Comment by joka** [comment]
bower requirejs-text#2.0.14                              ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/requirejs/text.git", exit code of #128 fatal: unable to access 'https://github.com/requirejs/text.git/': Empty reply from server

**Comment by der-john** [comment]
> mmh, i guess we had a similar problem in the past, I'll have a look.

Thank you!
