### ISSUE TITLE
Rename default "god" user to "admin"

### ISSUE THREAD

**Issue by slomo** [liqd/adhocracy3#2327]
I think we should rename it to be more secular.

**Comment by xi** [comment]
Should not be much work. There is `adhocracy.initial_login` in  the config.

**Comment by slomo** [comment]
Should we have migrations for this?

**Comment by joka** [comment]
> Should we have migrations for this?

This would prevent being confused who is the admin user.

**Comment by joka** [comment]
For security concerns  we should also make the admin user a normal user with the admin role instead of bypassing any security check.

**Comment by slomo** [comment]
I could also see it as a separate issue.
