### ISSUE TITLE
Update/improve glossary

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3#2343]
Our [glossary](http://adhocracy3.readthedocs.io/en/latest/glossary.html) is not up-to-date and not easy to understand. I think we could really benefit from improving it.

**Comment by joka** [comment]
+1

**Comment by xi** [comment]
In #2371 (after a long discussion) I added a separate "concepts" section that is targeted at a wider audience. The glossary is still referenced in backend docstrings.

I am still not convinced that the  backend glossary is very useful in its current form. We may want to remove (including all references in docstrings)

**Comment by der-john** [comment]
Won't be extended.
