### ISSUE TITLE
Follow-up: Introduce DELETE

### ISSUE THREAD

**Issue by der-john** [liqd/adhocracy3#2374]
DELETE has been implemented in #2365.

Some problems discussed in #2336 remain.

 *  [x] backup 'deleted' resources for 2 weeks
    i suggest extending the audit log and add a script to make it usable by sysadmins (@joka)
 *  [x] remove 'deleted' flag form metadata sheet (only used in Debate Workbench / `Document.ts`)
   as far as I can see. I suggest it be replaced by hide  ( @der-john)
 *  [x] check if delete permission is given
 *  [x] remove 'deleted field in IMetadata sheet in backend 
 *  ([ ] enable 'removed'/ 'removed_child' notification for the websocket api see #2700 )
 *  [x] remove special 'hidden' field for metadatda sheet in options requests (not needed anymore)
 *  [x] Fix delete in pools for versions (e.g. blog entries)

**Comment by joka** [comment]
I merged the remaining todos from https://github.com/liqd/adhocracy3/pull/2365

**Comment by xi** [comment]
I elevated this to high prio because of the backup feature which is critical

**Comment by der-john** [comment]
I was wrong about Debate Workbench / Document.ts: there is no delete action relating to the backend there at all (only a frontend attribute called `deleted` that makes a paragraph not be posted in the next version of the document).

**Comment by joka** [comment]
Removed high prio cause backup feature  is implemented
