### ISSUE TITLE
on deleting IdeaCollection proposal, user is redirected to Kiezkasse

### ISSUE THREAD

**Issue by Janaba** [liqd/adhocracy3#2387]
When Petra deleted a proposal, she was redirected from ISEK Tegel to Kiezkassen (standard). It should stay on ISEK Tegel.

**Comment by der-john** [comment]
I think it's a deployment question: the `redirect_url` needs to be set (differently). @2e2a could you look into this?

**Comment by der-john** [comment]
**Update**: It turns out it's not a deployment issue.
