### ISSUE TITLE
Can't build M2015 in `organisation/mercator` and then create proposal

### ISSUE THREAD

**Issue by der-john** [liqd/adhocracy3#2393]
I've removed the build folder, built adhocracy-mercator afresh, restarted the server, imported the process resource, set the workflow state to 'participate', browsed to my local a3, filled in the form and clicked on 'submit'.

The proposal isn't posted. In the UI it says:

```
"<InterfaceClass adhocracy_mercator.resources.mercator.IMercatorProposal>" is not one of <InterfaceClass adhocracy_core.resources.document_process.IDocumentProcess>, <InterfaceClass adhocracy_core.resources.organisation.IOrganisation>, <InterfaceClass adhocracy_core.resources.process.IProcess>, <InterfaceClass adhocracy_mercator.resources.mercator.IProcess>
```

**Comment by der-john** [comment]
@slomo just gave me the workaround: I imported the Mercator2015 process into `/organisation/`. THat did the trick.

**Comment by joka** [comment]
It would be usefull to have a test import fixture for mercator to prevent this kind of errors

**Comment by slomo** [comment]
Isn't this still a frontend code issue? Or are we saying won't fix here.

**Comment by der-john** [comment]
You're right.

**Comment by xi** [comment]
This process will probably not be used again, so it is not really relevant to fix it.
