### ISSUE TITLE
Can't upload PNG to (S1) user space

### ISSUE THREAD

**Issue by der-john** [liqd/adhocracy3#2396]
@dwt and I found this issue when testing s1:

Logged in to the functioning s1 site, we tried to upload an ordinary PNG file.

The Ui didn't react and the browser threw the following error message:
> "Claimed MIME type is image/png but file content seems to be application/octet-stream"

**Comment by dwt** [comment]
to reproduce:
* log in to s1
* go to your own users page
* click user image
* select image (png)
* try to submit

**Comment by joka** [comment]
guess its similar to #2273, the system dependencies to install python magic are not fullfilled: https://github.com/ahupp/python-magic , is libmagic-dev installed?

**Comment by dwt** [comment]
installing libmagic did fix this locally. However, uploading an image (jpg/png) still does`t seem to work.

To be more precise: uploading the image seems to work, but then downloading it again gives this error:

```
{
"errors": [
{
"location": "internal",
"name": "",
"description": "OSError: decoder jpeg not available; time: 2016-06-10 11:06:13,784"
}
],
"status": "error"
}
```

Maybe another dependency issue?

**Comment by dwt** [comment]
My googling seems to indicate that my Pillow installation lacks jpeg / zlib support. I do have all the necessary libraries installed though. Could you perhaps advise how I can check pillow is really lacking links to those libraries?

**Comment by dwt** [comment]
I just checked again by reinstalling pillow, and it supposedly has found the required dependencies:

```    --------------------------------------------------------------------
    PIL SETUP SUMMARY
    --------------------------------------------------------------------
    version      Pillow 3.2.0
    platform     darwin 3.5.1 (default, May  3 2016, 15:11:20)
                 [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.29)]
    --------------------------------------------------------------------
    --- TKINTER support available
    --- JPEG support available
    *** OPENJPEG (JPEG2000) support not available
    --- ZLIB (PNG/ZIP) support available
    --- LIBTIFF support available
    --- FREETYPE2 support available
    *** LITTLECMS2 support not available
    *** WEBP support not available
    *** WEBPMUX support not available
    --------------------------------------------------------------------```´

**Comment by dwt** [comment]
forget that, I was checking the wrong installation of pillow. :/

**Comment by dwt** [comment]
Works for me now after reinstalling the missing libraries (lzlib, libjpqeg) and then actually reinstalling adhocracy.

**Comment by joka** [comment]
All missing dependencies reported in this issue are documented. Also with merging
https://github.com/liqd/adhocracy3/pull/2407
https://github.com/liqd/adhocracy3/pull/2408 they are hard dependencies.
