### ISSUE TITLE
Simplify setup private processes

### ISSUE THREAD

**Issue by joka** [liqd/adhocracy3#2430]
Motivation:

We need to setup mixed private and public processes for S1 and the setup like for euth is quite complicated to understand.

Goal:

- Extending standard  workflow should be enough to setup private workflows in  the following use cases:  register users dis/enabled,  mixed/only private/public processes

Proposal:

- rename authenticated group in default_group (default user group for new created users)
- remove global participator role from default_group   (the need for global roles is platform specific and should not be the default)
- extend workflow definition with local rules : `add_local_role_participant_to_default_group: True`

Risks: 

   low, not complicated and no productive installation is modified, except the inital setup scripts should set the 'participator' role for the default group if wanted.

**Comment by joka** [comment]
I don't  now if 'default_group' is the semantically right name,  any other suggestions? maybe "users"?

**Comment by slomo** [comment]
Sound good. I wonder a bit what happens with all the other global resources? For instance in euth users didn't hat access to /principals/ after we disabled the default group. And same issue arises if process navigation is implemented.

**Comment by joka** [comment]
> Sounds good. I wonder a bit what happens with all the other global resources? For instance in euth users didn't hat access to /principals, /assets, or /catalogs after we disabled the default group.

yeah thats a drawback, we can set local view permissions for `authenticated` to fix this.

**Comment by joka** [comment]
also `/locations`
