### ISSUE TITLE
filtering for badges broken

### ISSUE THREAD

**Issue by der-john** [liqd/adhocracy3#2432]
I've built IdeaCollection on master, created a proposal P, given P badge X and deleted badge X from P again.

When I filter the proposal listing for "badge X":
- I'd expect **not** to see proposal P.
- I do see proposal P, though.

In the backend, proposal P doesn't have badge X, so I think it's the filter that's broken.

It was broken already in #2373. :(

Emptying my cache didn't fix it. :(

**Comment by der-john** [comment]
The backend seems to be lacking information. In
`http://localhost:6541/organisation/idea_collection/proposal_0000000/badge_assignments/?elements=contents`, there is no element displayed in the pool.

I talked to @2e2a and he said the bug might have been introduced by recent backend merges.

**Comment by 2e2a** [comment]
Index is not updated after badge deletion, I'll look into it.

**Comment by 2e2a** [comment]
> I talked to @2e2a and he said the bug might have been introduced by recent backend merges: This behavior doesn't happen on https://meinberlin-stage.liqd.net/w/.

The error does occur also on staging.

**Comment by 2e2a** [comment]
Fixed by #2463
