### ISSUE TITLE
add ActivityStream and notifcation system

### ISSUE THREAD

**Issue by joka** [liqd/adhocracy3#2475]
Proposal:
---------

- add global activity stream https://en.wikipedia.org/wiki/Activity_stream
- let user follow activity streams for specific resources
- notifiy followers by email about new activities
- allow other notifcations like daily digest, dashboard, ...

Nice to have constrains:

- use existing standards for data modelling / future activity stream API endpoint
- use human/machine readable data

Use Cases:
---------

1. Moderator is notified when a Proposal is added to a Process
2. Participant is notified about activity on his proposals/comments
   (This could mean: comment added, replied to comment, diskliked, liked, undo dis/liked)
3. Participant is notified about whats going on in his processes
   (This could mean: comment added, replied to comment, diskliked, liked, undo dis/liked,
                     state transition of process workflow)
4. User can turn notification on/off.
5. ( Sysadmin want to see what data was changed)
6. ( User can follow other user activities)
7. ( User can follow custom processes/contents)

Implementation:
---------------

- extend existing auditlog to serve as data source for activity stream entries (see `Data Model`)
- add indexes to search auditlog by date, subject, type, object, target
- add user sheet `INotification` to configure personal activity stream with fields:

    - `follow_resources`: list of  `IFolowable` resources 
    - `follow_notification`: Off, by_email, daily_digest, ...

- add sheet `IFollowable` to mark resources that can be followed ( for process, process content, users) 

- add system service `notifications` that  aggregates activity feeds and notifies followers:

       1. add new activities to persistent  activity stream

            - User1 add proposal1 to process1
            - User2 like proposal1

       2. generate resource activity streams for users, processes, content:

            - User1:
                 - User1 add proposal1 to process1
            - process1:
                - User1 add proposal1 to process1
                - User2 like proposal1

       3. Notify users following resource stream:

            - send adhoc email
            - aggregate activities for daily digest
            - ...

    For small plattforms we can do this after every commit, for larger platfforms maybe with an external process

Data Model for activity stream entries:
---------------------------------------

Based on W3C Activity stream v2 Ontology, extended by:

- `Transition` activity (changed workflow state)
- `Undo` activity uses the `target` property to reference the `object` of the undone activity

Entry:

           <subject>, <type>,  <object>,    <target>,    <name>,     <inreplyto>,    <published>

Example:

        1. /user1,    Add,     /proposal1,  /process1,   "User1 added a proposal to Process1"
        2. /user1,    Remove,  /proposal1,  /process1,   "User1 removed a proposal from Process1"
        3. /user1,    Update,  /proposal1,               "User1 edited a proposal"

        4. /user1,    Add,     /comment1,   /proposal1,  "User1 added a comment for Proposal1"
        5. /user1,    Add,     /comment1b,               "User1 replied to a comment"            /comment1
        6. /user1,    Remove,  /comment1,   /proposal1,  "User1 removed a comment for Proposal1"
        7. /user1,    Update,  /comment1,                "User1 edited a comment"

        8. /user1,    Flag,    /comment1,                "User1 flagged an inappropiate comment."
       81. /user1,    Undo,    8,           /comment1    "User1 nolonger flags an inappropiate comment."

        9. /user,     Like,    /proposal1,               "User1 liked Proposal1."
       10. /user,     Undo,    9            /proposal1   "User1 no longer likes Proposal1."
       11. /user,     Dislike, /proposal1                "User1 disliked Propopsal1."
       12. /user,     Undo,    10           /proposal1   "User1 no longer dislikes Proposal1."

       13.            Transition, /process1,             "Workflow1 changed phase to 'Frozen'."

The difference between Likes and Rates is hidden (except Rates may have the Dislike activity, Likes not)
The difference between versionable and non versionable resources is hidden (object for versionable is always the Item, not the ItemVersion)
The `Flag` activity is equal to `hide` a resource in our solution domain, `Remove` is equal to `delete`.

References:
-----------------

### Specs:

http://activitystrea.ms/
https://www.w3.org/TR/activitystreams-core/
https://www.w3.org/TR/activitystreams-vocabulary

### Implementations and software architectures:

http://de.slideshare.net/danmckinley/etsy-activity-feeds-architecture custom (weighted graph, aggregation)
https://github.com/ckan/ckan/wiki/Spec:-Activity-Stream-Notifications custom (python/pylons/sql)
http://django-activity-stream.readthedocs.io/ Activity Stream v1 (python/django/sql)
https://github.com/simonz05/activity-feed/ Activity Stream v2 (python/redis)
http://pythonhosted.org/ActivityStream/ Activity Stream v2 (python/mongodb)
https://www.cubicweb.org/project/cubicweb-activitystream  Activity Stream v1) (python/cubicweb/SQL)

**Comment by 2e2a** [comment]
Implmented by #2483
