### ISSUE TITLE
ideaCollection create_proposal looks broken

### ISSUE THREAD

**Issue by der-john** [liqd/adhocracy3#2513]
I built master, imported buergerhaushalt, set workflow state. Then I filled in the create_proposal form.

After clicking on submit, the proposal was successfully posted, **but** I got the following error:

```
XMLHttpRequest cannot load http://localhost:6541/batch. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:6551' is therefore not allowed access. The response had HTTP status code 500.
```

And also:

```
the request was aborted before it could reach the server
```

I've seen and prevented this error before, but I can't remember how. Can somebody help?

**Comment by xi** [comment]
What it says is: The preflight request returned status code 500 and did not contain an `Access-Control-Allow-Origin` header. The request was therefore aborted bu the client.

So the actual bug here is that the preflight request on `http://localhost:6541/batch` failed on the server side.

**Comment by der-john** [comment]
*Update*: The same errors occur on loading any workbench.

Has anyone reproduced this?

**Comment by der-john** [comment]
Vanished after reboot.
