### ISSUE TITLE
Forced uppercase first letter for tags and buttons

### ISSUE THREAD

**Issue by rittermo** [liqd/adhocracy3#2554]
I really like the new resource header for proposals. It looks very nice and the voting options as well as the title become much more clear. There is a small thing that has bugged me for some time: The automatic uppercase letters at the beginning of every word in buttons and tags (see screenshots). It produces grammatical mistakes in German as i.e. “Kommentar Erstellen” instead of “Kommentar erstellen” and it should be realtively quick and to turn it off. 
![bildschirmfoto 2016-07-28 um 09 16 36](https://cloud.githubusercontent.com/assets/15341015/17204244/bfc8ce0e-54a4-11e6-88c4-1fc3c2a68853.png)
![bildschirmfoto 2016-07-28 um 09 15 15](https://cloud.githubusercontent.com/assets/15341015/17204246/c1d1906e-54a4-11e6-93fa-836c256bffe4.png)

**Comment by xi** [comment]
Was introduced in 90706eab

**Comment by der-john** [comment]
I talked to @localgrr - she introduced the uppercases in 90706ea and totally agrees with reverting them.

**Comment by rittermo** [comment]
Wohoo! Thank you! The buttons look awesome now!
