### ISSUE TITLE
Badges get assigned to items/versions while filters work on the other one

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3#2572]
Tested in meinberlin kiezkasse, but potentially also an issue somewhere else.

We typically use badges in three places:

-  Assign them
-  Display them on the proposal detail page
-  Filter listing

For versionable resources, we typically display badges assigned to both version and item. But it is important that assignment and filtering work on the same resource, i.e. either version or item.

This regression was probably introduced when we moved badge assignment into the resource actions in #2459.

**Comment by der-john** [comment]
I did some research:
- Assigning badges: we currently assign badges to **items**. (In the proposal detail template, the resource dropdown always gets the item as its `resourcePath` and then in turns hands this to `adhBadgeAssignment`.)
- Filter listing for badges: we currently filter the **versions** of resources for badges. (In the process detail template, `adhListing` gets a version as its `contentType` and applies the badge facet to filtering these versions.)

As far as I can see, any solution must change something about one of these two mechanisms.

**Comment by der-john** [comment]
Thanks to @xi 's scrutiny I found out my second point is not quite correct:
- **updated** Filter listing for badges:
1. in `Comment`, `IdeaCollection`, `Alexanderplatz`, `DebateWorkbench` and `S1`, we currently filter the **versions** of resources for badges. (In the process detail template, `adhListing` gets a version as its `contentType` and applies the badge facet to filtering these versions.)
1. in `Process`, `Blog` (which are both not used), `UserList` and `Mercator`, we currently filter the **items** of resources for badges. (In the process detail template, `adhListing` gets an item as its `contentType` and applies the badge facet to filtering these items.)

**Comment by der-john** [comment]
I suggest changing 1. (assigning badges) for `IdeaCollection` and `S1`, i.e. we assign badges to proposal versions in `IdeaCollection` and `S1` again. It's the way it worked until #2478 and is easily implemented.

**Comment by xi** [comment]
To expand on the comment above:

-  In Mercator 2015, we do in fact filter versions
-  Processes, Blog posts, Users, and Mercator 2016 proposals are not versionable (aka simples) so they are **not** filtered by item as the version/item distinction does not make sense for them.
