### ISSUE TITLE
Stadtforum poll creation fails

### ISSUE THREAD

**Issue by 2e2a** [liqd/adhocracy3#2603]
Creating a poll for a stadtforum via the frontend fails:

Example: [https://meinberlin-stage.liqd.net/embed/meinberlin-stadtforum-proposal-create?poolPath=%2Ftest%2Fstadtforum%2F](https://meinberlin-stage.liqd.net/embed/meinberlin-stadtforum-proposal-create?poolPath=%2Ftest%2Fstadtforum%2)

It seems like the path parameter is missing in the batch request.

**Comment by xi** [comment]
This might well be an issue with the URL. It should definetely be something along the lines of https://meinberlin-stage.liqd.net/embed/meinberlin-stadtforum-proposal-create?pool-path=https:%2F%2Fmeinberlin-stage.liqd.net%2Fapi%2Ftest%2Fstadtforum%2F

**Comment by 2e2a** [comment]
> This might well be an issue with the URL. It should definetely be something along the lines of https://meinberlin-stage.liqd.net/embed/meinberlin-stadtforum-proposal-create?pool-path=https:%2F%2Fmeinberlin-stage.liqd.net%2Fapi%2Ftest%2Fstadtforum%2F

Works this way
