### ISSUE TITLE
Meta API does not deliver query response fields in pool sheet

### ISSUE THREAD

**Issue by mf59816** [liqd/adhocracy3#261]
I think this is a general bug, but it only shows on branch `2014-11-mf-rest-api-and-types+1`.

The last test case in `RateIg.ts` fails when running the integration tests.  (NOTE: always run the entire integration test files; the individual tests depend on each other!)

Reason: `/meta_api` claims that `adhocracy_core.sheets.pool.IPool` has no fields besides `element`.

This has gone undetected for a while, but recent changes in the way the frontend parses resources have the effect that all fields not mentioned in '/meta_api' are ignored.

I request that `/meta_api` is fixed such that all fields potentially contained in the pool sheet are specified.

To reproduce:

    $ curl "http://lig:6541/adhocracy/Against_Curtains_0.5825077714398503/rates/?content_type=adhocracy_core.resources.rate.IRateVersion&depth=2&tag=LAST&cou{
       "content_type" : "adhocracy_core.resources.rate.IRatesService",
       "path" : "http://lig:6541/adhocracy/Against_Curtains_0.5825077714398503/rates/",
       "data" : {
          "adhocracy_core.sheets.metadata.IMetadata" : {
             "item_creation_date" : "2014-11-20T10:17:08.022079+00:00",
             "creation_date" : "2014-11-20T10:17:08.022079+00:00",
             "creator" : "",
             "modified_by" : "",
             "modification_date" : "2014-11-20T10:17:08.022079+00:00",
             "deleted" : "false",
             "hidden" : "false"
          },
          "adhocracy_core.sheets.pool.IPool" : {
             "elements" : [
                "http://lig:6541/adhocracy/Against_Curtains_0.5825077714398503/rates/rate_0000000/VERSION_0000001/"
             ],
             "aggregateby" : {
                "rate" : {
                   "1" : 1
                }
             },
             "count" : "1"
          }
       }
    }
    $ curl "http://lig:6541/meta_api" | json_pp
    [...]
          "adhocracy_core.sheets.pool.IPool" : {
             "fields" : [
                {
                   "creatable" : false,
                   "containertype" : "list",
                   "valuetype" : "adhocracy_core.schema.AbsolutePath",
                   "readable" : true,
                   "name" : "elements",
                   "create_mandatory" : false,
                   "editable" : false,
                   "targetsheet" : "adhocracy_core.interfaces.ISheet"
                }
             ]
          },
    [...]

**Comment by joka** [comment]
nobody seems to be interested in this anymore
