### ISSUE TITLE
anonymization doesn't harmonize with user activity overview

### ISSUE THREAD

**Issue by der-john** [liqd/adhocracy3#2645]
I build S1.
I log in as participant.
I set my user anonymity default to `true`.
On the user activity overview, I see that participant has rated `n` times.
I rate a fresh proposal (a proposal I haven't rated before).

Then I revisit the user activity overview.
**Expected result:** I see that participant has rated `n` times.
**Actual result:** I see that participant has rated `n+1` times.

The cause seems to be the following: 
- by rating anonymously, an anonymous new version is created - the rate item itself lists participant as the creator. (That's what I see in meinberlin.)
- the user activity (in `src/adhocracy_frontend/adhocracy_frontend/static/js/Packages/User/Views.ts:890`) queries the backend for `RIRate`s with participant as their creator. Thus, the rate count increases. (As far as I know, the frontend cannot easily find out which rate version is the newest, as rate versions do not get the "LAST" tag.)

**Comment by der-john** [comment]
In my opinion, there are (at least) two possible solutions:
1. rate versions automatically get the "LAST" tag, the same way that proposals do. And the user activity overview queries the last version.
2. rates are made simple resources.

@dwt says he is afraid that, in the case of (1), logged-in users could still deanonymize rates by querying the backend, and favors (2). I personally currently think versioning rates is pointless, so I suggest (2) as well.

**Comment by joka** [comment]
I don't really understand how this happens. 
If you create a new anoymized rate item/version the backend should set the creator and rate subject to the anonymous user and not the authenticated user.

**Comment by joka** [comment]
> (As far as I know, the frontend cannot easily find out which rate version is the newest, as rate versions do not get the "LAST" tag.)

Like for all versionables, there is a always a rate version with LAST tag.

**Comment by joka** [comment]
regarding should rates be versionable or not:

I guess its the same like the general question if we want to use versioning, except the scalability and performance reasons are more demanding for rates.
For most of our use cases  the audit feature is enough.

**Comment by xi** [comment]
I do not think that this is fixed: If the rate version is anonymous, but the item is not, that effectively means that the whole rate is not anonymous. #2647 only hides that fact from the UI, but deanonymization is easily possible via the API.
