### ISSUE TITLE
IE11 doesn't always render our icon font

### ISSUE THREAD

**Issue by dwt** [liqd/adhocracy3#2646]
Sadly we have no Idea what exact set of preconditions trigger this bug. We cannot reproduce it on our boxes, but we saw it on all machines  at Stendal.

Some screenshots that show the problem are appended.

My analysis: something prevents the custom icon font from loading / showing in some configurations of windows.

Some common reasons would be that external font loading is disabled completely, or in the browser. However, we know that the previous deployment of S1 had working icons. So either they changed that setting recently, or we changed something about how we deploy that font file.
![image1](https://cloud.githubusercontent.com/assets/57199/18006732/505cf9dc-6ba1-11e6-82d2-4ac476ad9b3d.png)
![50929cd6-6ba1-11e6-8909-a0455f96aa15](https://cloud.githubusercontent.com/assets/457147/18049040/0cf759e8-6de6-11e6-96e2-0e2fced493c3.png)
![image3](https://cloud.githubusercontent.com/assets/57199/18006737/509e2768-6ba1-11e6-8caa-f04e856b2d07.png)
![image4](https://cloud.githubusercontent.com/assets/57199/18006734/5095f714-6ba1-11e6-808a-e0c608d5346d.png)
![image5](https://cloud.githubusercontent.com/assets/57199/18006736/509e3a3c-6ba1-11e6-95c7-e101ee89af06.png)
![image6](https://cloud.githubusercontent.com/assets/57199/18006735/509b0114-6ba1-11e6-8318-bdba458f880e.png)

**Comment by dwt** [comment]
Some more info: all of this is in IE11 (in this case on windows 7)

**Comment by dwt** [comment]
This was partially resolved in the pull request: #2653. However, the pencil icon is still missing (edit action for proposals uses it).

**Comment by dwt** [comment]
as visible on https://aastendal-stage.partou.org/r/aastendal/thementag-21-09-16/proposal_0000044/ when logged in as admin

**Comment by der-john** [comment]
@dwt, @xi and I have discussed a way to remap icons. stay tuned.
