### ISSUE TITLE
S1: Send message to user gives 500 errors on send

### ISSUE THREAD

**Issue by dwt** [liqd/adhocracy3#2667]
Sending a message fails with a 500er error:

```
{
    "status": "error",
    "errors": [{
        "location": "internal",
        "name": "",
        "description": "SMTPSenderRefused: (501, b'5.1.7 Bad sender address syntax', 'noreply@'); time: 2016-09-01 10:32:35,645"
    }
    ]
}

```

is what is visible in the console.

This may be a deployment issue.

**Comment by dwt** [comment]
I forgot this happens on aastendal-stage and on aastendal.

**Comment by nidico** [comment]
This is indeed just a deployment issue: `mail.noreply_sender` isn't configured.

**Comment by der-john** [comment]
**Note**: Since #2666 this can't be reproduced locally anymore.

**Comment by der-john** [comment]
> This is indeed just a deployment issue: mail.noreply_sender isn't configured.
