### ISSUE TITLE
Cannot update process-description in SDI without restarting varnish cache

### ISSUE THREAD

**Issue by dwt** [liqd/adhocracy3#2736]
When updating the iTitle or iDescription sheet of a process on production, those changes are not visible in the browser until the varnish cache is restarted. 

This means that either:
* The server doesn't correctly manage changed state and doesn't tell varnish that content needs to be reloaded
* Varnish is configured too aggressively and doesn't correctly validate with the backend server if content has changed.

Please fix.

To reproduce:
* Login to https://aastendal.partou.org/manage/aastendal/thementag-21-09-16/@@properties/IDescription
* Change something (minor please, this is a production system)
* Visit https://aastendal.partou.org/r/aastendal/thementag-21-09-16/ and look for those changes
* Notice that they are not visible
* Restart the varnish cache
* Reload and notice that the changes are visible.

**Comment by xi** [comment]
Is this related to #2521?

**Comment by nidico** [comment]
Looks like a different issue to me. Here, the new content is visible in the SDI after saving, but not in the user frontend. In #2521, the change isn't even reflected in the SDI.

**Comment by 2e2a** [comment]
> Is this related to #2521?

This is a different issue. The cache seems not to be invalidated on changes made via SDI. I will look into it.

**Comment by 2e2a** [comment]
Cannot reproduce.

PURGE requests are send by the backend to varnish when the description is updated as expected. Changes appear in the frontend.
