### ISSUE TITLE
SDI erroneously shows login dialog on /api/manage

### ISSUE THREAD

**Issue by nidico** [liqd/adhocracy3#2737]
The SDI should be accessed throug `/manage`. However opening `/api/manage` also shows the same login dialog, however it doesn't accept any credentials.

This is very confusing and should be fixed, probably through a redirect or by not showing the login form on `/api/manage`.

**Comment by 2e2a** [comment]
Requests to /api/manage go through varnish, which deletes the authentication cookies.

As a quick solution we have configured nginx to send request to /manage directly to the backend. I will change the varnish settings to fix this.

**Comment by 2e2a** [comment]
Updated deployment:
* /api/manage works now, as varnish allows the sdi cookies
* /manage redirects to /api/manage
