### ISSUE TITLE
S1: Renominate broken for normal users

### ISSUE THREAD

**Issue by dwt** [liqd/adhocracy3#2739]
It does work for admins though.

To reproduce:
* Visit https://aastendal-stage.partou.org/manage/
* Create a user, with the group 'participants-aastendal'
* Login with that user
* Go to 'archive'
* Select a proposal that has **NOT** won
* Click the renominate button that is visible (it won't show for proposals that have been accepted already)
* A dialog box should show up telling the user that the page will reload is shown
* that reload does not happen
* the proposal is also not renominated.

It does work as admin though.

The JS console also shows these errors:
```
[Error] Array (1)
0 Object

code: 400

description: "Unrecognized keys in mapping: \"{'adhocracy_core.sheets.workflow.IWorkflowAssignment': {'workflow_state': 'proposed'}}\""

location: "body"

name: "data"

Object Prototyp

Array Prototyp

	(anonyme Funktion) (angular.min.js:90:234)
	(anonyme Funktion) (angular.min.js:131:105)
	$digest (angular.min.js:142:426)
	$apply (angular.min.js:146:121)
	l (angular.min.js:97:329)
	J (angular.min.js:102)
	onload (angular.min.js:103)
```

**Comment by 2e2a** [comment]
Tested it locally and on stating.

A user can renominate only its own proposal. This error occurs when trying to renominate a proposal from another user.

From my perspective it makes sense this way and the actual problem is that we show the renominate button also for proposals that belong to other users.

**Comment by 2e2a** [comment]
According to @dwt in the specification of the feature all participants should be able to renominate.
