### ISSUE TITLE
in "debate ideaCollection", process options behave unexpectedly

### ISSUE THREAD

**Issue by der-john** [liqd/adhocracy3#2745]
In the new "debate ideaCollection" (cf. https://tree.taiga.io/project/ggr-meinberlinteam/us/458?milestone=93539), regular users shouldn't be able to create proposals - this is a requirement.

@2e2a said he achieved this by setting the process's `workflow` to `debate`. But unfortunately, in the frontend `processOptions.POST` returns `true`, which is why the "add proposal" button is displayed. As a regular user, I was even able to create a proposal.

**Comment by xi** [comment]
I cannot reproduce this. For me, everything works as expected.
