### ISSUE TITLE
Missing element name in collaborative text listing

### ISSUE THREAD

**Issue by 2e2a** [liqd/adhocracy3#2770]
https://meinberlin-stage.liqd.net/w/prozesse/collaborative_text/#!r/test/collaborative_text/

Shows "3" instead of "3 Dokumente" in the listing header.

**Comment by der-john** [comment]
I can't reproduce it: For me it says "3 Resources". This is probably not optimal. But, unfortunately, there is a name clash: In `mercator`, document resources are called "blog entries". We'd have to use a mechanism to distinguish between these two use cases of document.

**Comment by 2e2a** [comment]
Seems to be fixed.
