### ISSUE TITLE
Inconsistent workflow assignment state_data returned

### ISSUE THREAD

**Issue by 2e2a** [liqd/adhocracy3#2786]
On the paas staging server the backend returns different values for the IWorkflowAssignment state_date field of a process ([https://aastendal-stage.partou.org/r/aastendal/thementag-21-09-16/](https://aastendal-stage.partou.org/r/aastendal/thementag-21-09-16/)).

When requesting a process directly on the server (bypassing cache) the backend returns different state_date values, sometimes empty, sometimes the current value. During previous tests it seemed also to return an old value.

Also reloading the sheet view  often in SDI shows the problem:
[https://aastendal-stage.partou.org/api/manage/aastendal/thementag-21-09-16/@@properties/IWorkflowAssignment](https://aastendal-stage.partou.org/api/manage/aastendal/thementag-21-09-16/@@properties/IWorkflowAssignment)

@joka Any idea what could cause this?

This has high prio, as it breaks the decision_date mapping.

**Comment by joka** [comment]
How to reproduce?  
When I  tried to reloading https://aastendal-stage.partou.org/api/manage/aastendal/thementag-21-09-16/@@properties/IWorkflowAssignment multiple times the value did not change.

**Comment by joka** [comment]
ah ok, you need to wait a bit and than try again.

**Comment by 2e2a** [comment]
> ah ok, you need to wait a bit and then try again.

Did you have a look? Any suggestions?

**Comment by joka** [comment]
I tried to dig into it but cannot reproduce this anymore: 

- check source code regarding assignment data for mutable default values or similar errors
- check source code if assignment data is stored persistent
- tests (disabled browser and varnish cache):

             - change assignment data and restart database/backend process
             - change assignment data of multiple resources 
             - change assignment data, reload SDI multiple times, wait 10 minutes, reload again
