### ISSUE TITLE
User link in proposal element not working

### ISSUE THREAD

**Issue by 2e2a** [liqd/adhocracy3#2791]
When clicking on the user link of a proposal element in a proposal list (e.g. idea collection), the proposal is opened instead of the user page.

**Comment by der-john** [comment]
I've noticed this. I propose that I remove the link from the username on proposal list items.

**Comment by xi** [comment]
This is a general issue and we never really discussed it in detail. But I can remember that some points came up:

-  nested `<a>` elements are not valid in HTML
-  github (and potentially other sites) solve this by not wrapping the complete list item in a link. Instead, they wrap the title, image and some other parts. You can see this on the issues listing, where you can still click the user name.

**Comment by der-john** [comment]
I suggest a fixup.
