### ISSUE TITLE
PAAS user column on master slightly broken

### ISSUE THREAD

**Issue by der-john** [liqd/adhocracy3#2814]
On the S1 user profile page, the header gets partially covered by adhocracy content. Probably caused by #2805.

![paas-design kaputt](https://cloud.githubusercontent.com/assets/16540898/19676559/4ddda5ee-9a95-11e6-9c9b-a357c4fee377.png)

**Comment by der-john** [comment]
Still there. Sorry.

**Comment by xi** [comment]
For me it works fine. Can you please provide more information?

**Comment by der-john** [comment]
Couldn't reproduce.
