### ISSUE TITLE
Familienumfrage: embed not large enough

### ISSUE THREAD

**Issue by rittermo** [liqd/adhocracy3#2885]
Hey, the embed for the Familienumfrage on meinberlin productive is really small on my browser (Safari 10.0.2), so that it is barely usable. Can we do something about it?

https://mein.berlin.de/w/prozesse/kennen-sie-den-internationalen-tag-der-familie-am-/

<img width="733" alt="bildschirmfoto 2017-05-04 um 14 51 11" src="https://cloud.githubusercontent.com/assets/15341015/25704289/26ef2aae-30d9-11e7-9d8c-6453c8da4b7b.png">

**Comment by rittermo** [comment]
Hello, @xi, any idea why this happens?

**Comment by xi** [comment]
The size of the iframe is defined by the embedding side, not adhocracy. Can you please report the issue there?
