### ISSUE TITLE
Routing failures do not always produce an error.

### ISSUE THREAD

**Issue by mf59816** [liqd/adhocracy3#419]
Instead, parts of the page will just stay blank.  See #403 for more details on the symptoms.

To reproduce:

1. visit 4bab0224.
2. build everything.
3. load /r/mercator.  => routing failure, but no error!
4. `perl -i -pe s/RIBasicPool/RIPoolWithAssets/g src/mercator/static/js/Packages/MercatorWorkbench/MercatorWorkbench.ts`
5. load /r/mercator again  => routing success.

(If you don't like 4bab0224, you can also get the same effect by going to an arbitrary commit and putting an arbitrary wrong type in place of the above.)

**Comment by xi** [comment]
Fixed in 823ff057c6cd56f28d2de9f7f6ae417841ff613c
