### ISSUE TITLE
hiding a comment results in wrong comment count

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3#549]
In the frontend, we build the following query parameters to get the recursive comment count of a resource:

```
var query = {
    content_type: RICommentVersion.content_type,
    depth: "all",
    tag: "LAST",
    count: "true"
};
```

If I now hide (delete) a comment that has `n` replies, I expect the comment count to decrease by `n + 1`. Instead, it only decreases by `1`.

This is possibly because we do not reflect the comment structure in resource structure, i.e. all comments are in the same pool. This way, replies are not automatically hidden if the parent is hidden.

**Comment by xi** [comment]
I will close this because AFAIU this is intended behavior.

**Comment by nidico** [comment]
No, this isn't intended as it is. In my opinion, there are two "valid" possibilities:

- Prune the whole subtree (this is what we do). Then we should also not count the whole subtree.
- Explicitly mark the deleted item as "deleted", but show the subordinate comments. The counter should then still show the full count.

Reopening. It's not clear to me how to resolve it though.

**Comment by xi** [comment]
When I talked to the designers, the current behavior is exactly what they told me.

**Comment by xi** [comment]
This issue still exists with the new method of getting comment count introduced in #1958.

**Comment by pallix** [comment]
Is it still the case? There was some fixes that changed the behavior.

**Comment by xi** [comment]
Yes, the issue still exists.

**Comment by pallix** [comment]
Removing frontend flag as the information from the frontend is retrieved from 'comment_counts'.
