### ISSUE TITLE
adding HTTP security headers

### ISSUE THREAD

**Issue by mkind** [liqd/adhocracy3#614]
This is not criticial, but there are some nice HTTP security relevant header fields that might be worth setting (e.g. CSP, nosniff, X-Frame-Options). For header details, take a look at the [OWASP site](https://www.owasp.org/index.php/List_of_useful_HTTP_headers).

**Comment by xi** [comment]
Related to #2318

**Comment by xi** [comment]
#2318 deals with this issue in a more concrete way, so I am closing this.
